---

- name: "Create service credentials group"
  group:
    name: "{{ item.credentials.name }}-credentials"
    system: true
  loop: "{{ float_host_service_credentials }}"

- name: "Create service credentials dirs"
  file:
    path: "/etc/credentials/x509/{{ item.credentials.name }}"
    state: directory
  loop: "{{ float_host_service_credentials }}"

- name: Copy CA
  copy:
    src: "{{ credentials_dir }}/x509/ca.pem"
    dest: "/etc/credentials/x509/{{ item.credentials.name }}/ca.pem"
    owner: root
    group: root
    mode: 0644
  loop: "{{ float_host_service_credentials }}"

