---

- name: "Create {{ credentials.name }}-credentials group"
  group:
    name: "{{ credentials.name }}-credentials"
    system: true

- name: Create service credentials dir
  file:
    path: "/etc/credentials/x509/{{ credentials.name }}"
    state: directory

- name: Copy CA
  copy:
    src: "{{ credentials_dir }}/x509/ca.pem"
    dest: "/etc/credentials/x509/{{ credentials.name }}/ca.pem"
    owner: root
    group: root
    mode: 0644

- include_tasks: install_cert.yml
  with_items:
    - client
    - server
  when: "credentials.get('enable_' + mode, True)"
  loop_control:
    loop_var: mode
