---

#- set_fact:
#    x509_params: "{{ float_service_credentials_params[service_name_item + '-' + credentials.name] | default({}) }}"
#  when: "service_name_item is defined"

- name: Set up internal PKI credentials
  block:

    - file:
        path: "/etc/credentials/x509/{{ item.credentials.name }}/{{ item.mode }}"
        state: directory
      loop: "{{ float_host_service_credentials_certs }}"

    - name: "Check the internal PKI certificates"
      x509_csr:
        credentials_name: "{{ item.credentials.name }}"
        domain: "{{ domain }}"
        mode: "{{ item.mode }}"
        params: "{{ item.x509_params|default({}) }}"
        private_key_path: "/etc/credentials/x509/{{ item.credentials.name }}/{{ item.mode }}/private_key.pem"
        cert_path: "/etc/credentials/x509/{{ item.credentials.name }}/{{ item.mode }}/cert.pem"
        ca_cert_path: "/etc/credentials/x509/{{ item.credentials.name }}/ca.pem"
        check: true
      loop: "{{ float_host_service_credentials_certs }}"
      check_mode: no
      register: x509_should_update

    # TODO: set the right permissions (credentials.name-credentials)
    - name: "Create internal PKI CSRs"
      x509_csr:
        credentials_name: "{{ item.0.credentials.name }}"
        domain: "{{ domain }}"
        mode: "{{ item.0.mode }}"
        params: "{{ item.0.x509_params|default({}) }}"
        private_key_path: "/etc/credentials/x509/{{ item.0.credentials.name }}/{{ item.0.mode }}/private_key.pem"
        check: false
      when: "item.1.changed"
      loop: "{{ float_host_service_credentials_certs | zip(x509_should_update.results) | list }}"
      register: x509_csr

    - name: "Sign internal PKI certificates"
      x509_sign:
        csr: "{{ item.1.csr }}"
        mode: "{{ item.0.mode }}"
        ca_cert_path: "{{ credentials_dir }}/x509/ca.pem"
        ca_key_path: "{{ credentials_dir }}/x509/ca_private_key.pem"
      when: "item.1.changed"
      loop: "{{ float_host_service_credentials_certs | zip(x509_csr.results) | list }}"
      register: x509_sign

    - name: "Install the signed internal PKI certificates"
      copy:
        dest: "/etc/credentials/x509/{{ item.0.credentials.name }}/{{ item.0.mode }}/cert.pem"
        content: "{{ item.1.cert }}"
        mode: 0644
      when: "item.1.changed"
      loop: "{{ float_host_service_credentials_certs | zip(x509_sign.results) | list }}"

    - name: "Set permissions on the private keys"
      file:
        path: "/etc/credentials/x509/{{ item.credentials.name }}/{{ item.mode }}/private_key.pem"
        group: "{{ item.credentials.name }}-credentials"
        mode: 0640
      loop: "{{ float_host_service_credentials_certs }}"

  rescue:
    - debug:
        msg: "Failed to set up one or more credentials"

