---

- set_fact:
    x509_params: "{{ float_service_credentials_params[service_name_iter + '-' + credentials.name] | default({}) }}"
  when: "service_name_iter is defined"

- file:
    path: "/etc/credentials/x509/{{ credentials.name }}/{{ mode }}"
    state: directory

- name: "Check the certificate for {{ credentials.name }}/{{ mode }}"
  x509_csr:
    credentials_name: "{{ credentials.name }}"
    domain: "{{ domain }}"
    mode: "{{ mode }}"
    params: "{{ x509_params|default({}) }}"
    private_key_path: "/etc/credentials/x509/{{ credentials.name }}/{{ mode }}/private_key.pem"
    cert_path: "/etc/credentials/x509/{{ credentials.name }}/{{ mode }}/cert.pem"
    ca_cert_path: "/etc/credentials/x509/{{ credentials.name }}/ca.pem"
    check: true
  check_mode: no
  register: x509_should_update

# TODO: set the right permissions (credentials.name-credentials)
- name: "Create the CSR for {{ credentials.name }}/{{ mode }}"
  x509_csr:
    credentials_name: "{{ credentials.name }}"
    domain: "{{ domain }}"
    mode: "{{ mode }}"
    params: "{{ x509_params|default({}) }}"
    private_key_path: "/etc/credentials/x509/{{ credentials.name }}/{{ mode }}/private_key.pem"
    check: false
  when: "x509_should_update.changed"
  register: x509_csr

- name: "Create the certificate for {{ credentials.name }}/{{ mode }}"
  x509_sign:
    csr: "{{ x509_csr.csr }}"
    mode: "{{ mode }}"
    ca_cert_path: "{{ credentials_dir }}/x509/ca.pem"
    ca_key_path: "{{ credentials_dir }}/x509/ca_private_key.pem"
  when: "x509_should_update.changed"
  register: x509_sign

- name: "Install the signed certificate for {{ credentials.name }}/{{ mode }}"
  copy:
    dest: "/etc/credentials/x509/{{ credentials.name }}/{{ mode }}/cert.pem"
    content: "{{ x509_sign.cert }}"
    mode: 0644
  when: "x509_sign.changed"

- name: Set permissions on the private key
  file:
    path: "/etc/credentials/x509/{{ credentials.name }}/{{ mode }}/private_key.pem"
    group: "{{ credentials.name }}-credentials"
    mode: 0640
