---

# Distribute the SSO public key to all hosts.

- file:
    path: /etc/sso
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install SSO public key
  copy:
    src: "{{ credentials_dir }}/sso/public.key"
    dest: /etc/sso/public.key
    mode: 0644

# Distribute X509 credentials to all hosts as needed. This role works
# in combination with the 'x509' action plugin.

# X509 credentials are stored in /etc/credentials/x509 under
# directories named after the services. Every service directory
# contains a copy of the public CA certificate, so it can be
# bind-mounted in a container easily.

# Private keys have mode 440, are owned by root and by a dedicated
# group named <service>-credentials. When the service is actually
# installed, later, maybe by an Ansible role, it can add the service
# user to this group.

- name: Install x509ca package
  apt:
    name: x509ca
    state: present

- include_tasks: install_credentials.yml
  with_items: "{{ default_service_credentials|default([]) }}"
  loop_control:
    loop_var: credentials

- include_tasks: install_service.yml
  with_items: "{{ float_enabled_services }}"
  loop_control:
    loop_var: service_name_iter

# Remove credentials that shouldn't be here.
# - file: path="/etc/credentials/x509/{{ item.1.name }}" state=absent
#   with_subelements:
#     - "{{ services }}"
#     - service_credentials
#     - { skip_missing: true }

# Create a group for public credentials.
- name: Create public-credentials group
  group:
    name: public-credentials
    system: yes

# Create the root directory for public credentials.
- file:
    path: /etc/credentials/public
    state: directory
