---
- hosts: all
  tasks:
    - copy:
        src: ../roles/float-base/files/apt/deb_autistici_org.gpg
        dest: /usr/share/keyrings/deb.autistici.org.gpg
    - apt:
        update_cache: yes
        upgrade: "yes"
    - apt:
        autoremove: yes
  serial:
    - 1
    - 2
    - "100%"
