---

# Playbook that runs the float infra roles on 'frontend' hosts.

- hosts: frontend
  gather_facts: no
  roles:
    - float-infra-nginx
    - float-infra-haproxy

- hosts: dns
  gather_facts: no
  roles:
    - float-infra-dns

- hosts: admin_dashboard
  gather_facts: no
  roles:
    - float-infra-admin-dashboard

- hosts: acme
  gather_facts: no
  roles:
    - float-infra-acme

- hosts: reports_collector
  gather_facts: no
  roles:
    - float-infra-reports-collector

