---

# Playbook that runs the float infra roles on 'frontend' hosts.

- hosts: frontend
  gather_facts: no
  roles:
    - float-infra-nginx
    - float-infra-dns
    - float-infra-haproxy

- hosts: admin-dashboard
  gather_facts: no
  roles:
    - float-infra-admin-dashboard

- hosts: acme
  gather_facts: no
  roles:
    - float-infra-acme

- hosts: reports-collector
  gather_facts: no
  roles:
    - float-infra-reports-collector

