---

# Generate *all* local credentials at once, on localhost.

# This is better than having tasks with 'local_action' and 'run_once',
# mostly because the semantics of 'run_once' are odd (the task may be
# executed multiple times, depending on grouping done by the Ansible
# scheduler). But it is a bit less elegant than automatically creating
# what is necessary close to where it is used... on the other hand,
# this closeness is already missing for services like SSO where the
# public and secret parts are handled by separate roles.

- hosts: localhost
  gather_facts: no
  become: no
  tasks:
    # Check that "float" is properly set up.
    - include_role:
        name: float-plugin-check

    # Create the paths below credentials_dir that we're going to use.
    - name: "Create paths below {{ credentials_dir }}"
      file:
        path: "{{ credentials_dir }}/{{ item }}"
        state: directory
      with_items:
        - dkim
        - dnssec
        - ssh
        - sso
        - x509

    # First of all, generate secrets from the passwords.yml file.
    - name: Initialize secrets
      local_action: command ../scripts/pwgen.py --vars "{{ credentials_dir }}/secrets.yml" "{{ passwords_file }}"
      register: pwgen_result
      changed_when: "pwgen_result.rc == 1"
      failed_when: "pwgen_result.rc > 1"

    - name: Link secrets.yml from the vars directory
      file:
        src: "../../credentials/secrets.yml"
        dest: "{{ vars_dir }}/secrets.yml"
        state: link

    - name: Generate SSH CA
      local_action: sshca ca="{{ credentials_dir }}/ssh/key"
      when: enable_ssh

    - name: Generate SSO credentials
      local_action: ed25519 privkey="{{ credentials_dir }}/sso/secret.key" pubkey="{{ credentials_dir }}/sso/public.key"

    - name: Generate global DH params
      local_action: command openssl dhparam -out "{{ credentials_dir }}/x509/dhparam" "{{ dhparam_bits | default('2048') }}" creates="{{ credentials_dir }}/x509/dhparam"

    - name: Generate the X509 CA certificate
      local_action: x509_ca ca_subject="{{ x509_ca_subject | default('CN=Service CA') }}" ca_cert_path="{{ credentials_dir }}/x509/ca.pem" ca_key_path="{{ credentials_dir }}/x509/ca_private_key.pem"
