- hosts: prometheus-lts
  roles:
    - float-infra-prometheus-lts

# Configure 'thanos query' on 'prometheus' hosts to discover prometheus-lts
- hosts: prometheus
  roles:
    - float-infra-thanos-query-lts
