---

# Install podman from the A/I package repository. This is a "known
# good" version that works on Debian Buster.
#
# Some dependencies need to be pulled from buster-backports.

- name: Remove podman Kubic repository key
  file:
    path: "/etc/apt/trusted.gpg.d/kubic.gpg"
    state: absent

- name: Remove Kubic podman repository
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /"
    state: absent

- name: Add A/I podman repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/deb.autistici.org.gpg] http://deb.autistici.org/urepo buster-podman/"
    state: present

- name: Pin podman packages to our repository
  copy:
    dest: "/etc/apt/preferences.d/99podman"
    content: |
        Package: podman
        Pin: origin deb.autistici.org
        Pin-Priority: 1001

- name: Install podman packages
  apt:
    name: podman
    state: present
    default_release: "{{ 'buster-backports' if float_debian_dist == 'buster' else '' }}"

# TODO: remove this once the podman packaging issues are fixed.
- name: Install a working seccomp.json
  copy:
    src: "seccomp-0.3.2.json"
    dest: "/usr/share/containers/seccomp.json"
