---

# Pick a package source for Podman - defaults to using the stock
# Debian package since bullseye. Possible choices are 'ai' (a version
# pinned in our repository, tested working on Debian buster), 'debian'
# (use standard Debian packages, only available from bullseye) or
# 'kubic' (use the upstream Kubic repositories, with the latest
# release).
- set_fact:
    podman_default_package_source: "{{ podman_default_package_source_by_distro[float_debian_dist] | default('debian') }}"
- set_fact:
    podman_package_source: "{{ podman_default_package_source }}"
  when: "podman_package_source is not defined"

- include_tasks: "podman_{{ podman_package_source }}.yml"

# Try to detect which podman version we're on based on source and
# distribution.
- set_fact:
    podman_version: "{{ 3 if float_debian_dist in ('buster', 'bullseye') else 4 }}"
  when: "podman_package_source == 'debian'"
- set_fact:
    podman_version: 4
  when: "podman_package_source != 'debian'"

# If we've changed sources.list for podman, it is important
# that we run apt upgrade now.
- name: Apt upgrade
  apt:
    upgrade: 'yes'
  when: "podman_sources_list is defined and podman_sources_list.changed"

- name: Symlink podman to docker
  file:
    src: /usr/bin/podman
    dest: /usr/bin/docker
    state: link
    force: true

- name: Install containers.conf
  copy:
    src: containers.conf
    dest: "/etc/containers/containers.conf"

- name: Install storage.conf
  copy:
    src: storage.conf
    dest: "/etc/containers/storage.conf"

- file:
    path: "/etc/containers/certs.d"
    state: directory
  when: "podman_additional_ssl_ca is defined"

- name: Install custom CA for podman
  copy:
    dest: "/etc/containers/certs.d/additional.crt"
    content: "{{ podman_additional_ssl_ca }}\n"
  when: "podman_additional_ssl_ca is defined"

- name: Install HTTPS proxy for podman
  copy:
    dest: "/etc/containers/proxy-settings.sh"
    content: "export https_proxy={{ podman_https_proxy }}\n"
  when: "podman_https_proxy is defined"

