---

# Install Podman from the upstream "kubic" repository. This is usually
# the latest Podman release.


- name: Add podman Kubic repository key
  copy:
    src: "kubic.gpg"
    dest: "/etc/apt/trusted.gpg.d/kubic.gpg"

- name: Remove A/I podman repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/deb.autistici.org.gpg] http://deb.autistici.org/urepo buster-podman/"
    state: absent

- name: Add Kubic podman repository
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /"
    state: present

- name: Remove podman package pins
  file:
    path: "/etc/apt/preferences.d/99podman"
    state: absent

# Podman Kubic packages on buster require a version of libseccomp2
# from the backports.
- name: Install libseccomp2 from backports
  apt:
    name: libseccomp2
    state: present
    default_release: buster-backports
  when: "float_debian_dist == 'buster'"

- name: Install podman packages
  apt:
    name: podman
    state: present
