---

- include_tasks: "podman_{{ podman_package_source }}.yml"

# If we've changed sources.list for podman, it is important
# that we run apt upgrade now.
- name: Apt upgrade
  apt:
    upgrade: 'yes'
  when: "podman_sources_list.changed"

- name: Symlink podman to docker
  file:
    src: /usr/bin/podman
    dest: /usr/bin/docker
    state: link
    force: true

- name: Install containers.conf
  copy:
    src: containers.conf
    dest: "/etc/containers/containers.conf"

- name: Install storage.conf
  copy:
    src: storage.conf
    dest: "/etc/containers/storage.conf"

- file:
    path: "/etc/containers/certs.d"
    state: directory
  when: "podman_additional_ssl_ca is defined"

- name: Install custom CA for podman
  copy:
    dest: "/etc/containers/certs.d/additional.crt"
    content: "{{ podman_additional_ssl_ca }}\n"
  when: "podman_additional_ssl_ca is defined"

- name: Install HTTPS proxy for podman
  copy:
    dest: "/etc/containers/proxy-settings.sh"
    content: "export https_proxy={{ podman_https_proxy }}\n"
  when: "podman_https_proxy is defined"

