---

- include_tasks: "podman_{{ podman_package_source }}.yml"

- name: Symlink podman to docker
  file:
    src: /usr/bin/podman
    dest: /usr/bin/docker
    state: link
    force: true

- name: Install containers.conf
  copy:
    src: containers.conf
    dest: "/etc/containers/containers.conf"

