{
 "title": "Syslog",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(up{job=\"rsyslog\"}, host)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(up{job=~\"rsyslog.*\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Logs sent (rsyslog omfwd actions/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsyslog_action_processed:rate5m{job=\"rsyslog\",action=\"action-2-builtin:omfwd\",host=~\"^$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsyslog_queue_discarded:rate5m{job=\"$job\",host=~\"$host\"} > 0",
     "legendFormat": "{{host}}/{{queue}}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queue size (in-memory)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsyslog_queue_size{job=\"$job\",queue=~\".*(omfwd|omelasticsearch) queue\",host=~\"$host\"}",
     "legendFormat": "{{host}}/{{queue}}"
    }
   ]
  },
  {
   "title": "Queue size (disk)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsyslog_queue_size{job=\"$job\",queue=~\".*(omfwd|omelasticsearch).*\\\\[DA\\\\]\",host=~\"$host\"}",
     "legendFormat": "{{host}}/{{queue}}"
    }
   ]
  },
  {
   "title": "Queue full",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsyslog_queue_full{job=\"$job\",queue=~\".*(omfwd|omelasticsearch).*\",host=~\"$host\"}",
     "legendFormat": "{{host}}/{{queue}}"
    }
   ]
  },
  { "title": "Trouble", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Suspended Actions",
   "type": "table",
   "description": "Rsyslog is having trouble sending messages to some destinations, check its logs to figure out why.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rsyslog_action_suspended) without (instance, job, service) > 0"
    }
   ]
  }
 ]
}