# use the sspki role to create the credentials directory:
# the sspki role should create the api endpont cert, and the full chain bundle
# (containing the API endpoint CA and the generated cert) and install them

- include_role:
    name: sspki
  vars:
    sspki:
      name: vpnweb
      SANs:
        - "{{ provider_config.api_domain }}"
        - "{{ provider_config.provider_domain | default('')}}"
      ca: "{{ credentials_dir }}/common/api_ca.crt"
      ca_key: "{{ credentials_dir }}/common/api_ca.key"

- name: Restart nginx because certificate has changed
  systemd:
    name: nginx.service
    state: restarted
  when: sspki_sign.changed

- name: Add the nginx user to the vpnweb-sspki group
  user:
    name: nginx
    groups: vpnweb-sspki
    append: yes

- name: Install vpnweb nginx configuration
  template:
    src: vpnweb.conf.j2
    dest: /etc/nginx/sites-available/vpnweb.conf
  notify: reload NGINX

- name: Enable vpnweb nginx configuration
  file:
    dest: /etc/nginx/sites-enabled/vpnweb.conf
    src: ../sites-available/vpnweb.conf
    state: link
  notify: reload NGINX

- name: Install firewall config for vpnweb
  copy:
    src: "50vpnweb.firewall"
    dest: "/etc/firewall/filter.d/50vpnweb"
  notify: "reload firewall"
