- include_role:
    name: sspki
  vars:
    sspki:
      name: vpnweb
      ca: "{{ credentials_dir }}/common/api_ca.crt"
      ca_key: "{{ credentials_dir }}/common/api_ca.key"
  notify: reload NGINX

- name: Install vpnweb nginx configuration
  template:
    src: vpnweb.conf.j2
    dest: /etc/nginx/sites-available/vpnweb.conf
  notify: reload NGINX

- name: Enable vpnweb nginx configuration
  file:
    dest: /etc/nginx/sites-enabled/vpnweb.conf
    src: ../sites-available/vpnweb.conf
    state: link
  notify: reload NGINX
