hosts:
  floatapp1:
    ansible_host: 37.218.241.84
    groups: [backend]
    ip: 37.218.241.84
    # The 'ip_vpn0' is for the internal network overlay only. Assign an unique
    # value for each host
    ip_vpn0: 172.16.1.1
  floatrp1:
    ansible_host: 37.218.241.85
    groups: [frontend]
    ip: 37.218.241.85
    # The 'ip_vpn0' is for the internal network overlay only. Assign an unique
    # value for each host
    ip_vpn0: 172.16.1.2
  gateway1:
    ansible_host: 37.218.242.191
    groups: [openvpn]
    ip: 37.218.242.191
    # The 'ip_vpn0' is for the internal network overlay only. Assign an unique
    # value for each host
    ip_vpn0: 172.16.1.3
    # Set the egress source address for ipv4. This address should be distinct
    # from the 'ip' value above to prevent traffic leaks.
    egress_ip: 37.218.242.216
    location: Amsterdam
  gateway2:
    ansible_host: 204.13.164.252
    groups: [openvpn]
    ip_vpn0: 172.16.1.4
    ip: 204.13.164.252
    # If the gateway has ipv6, assign it an address here. This address will be
    # used as the incoming ipv6 address for the gateway.
    ip6: 2620:13:4000:4000:8080::252
    # Set the egress source address for ipv4. This address should be distinct
    # from the 'ip' value above to prevent traffic leaks.
    egress_ip: 204.13.164.84
    # For each gateway that has ipv6, you should allocate an ipv6 netblock
    # (probably a /64) for each gateway. This ipv6 netblock should be in a
    # different network than the ip6 address that you configured above.
    # Openvpn will allocate IPs from this pool automatically, and they will
    # be used for egress source addresses.
    openvpn_network6: "2001:db8:123::/64"
    location: Seattle
group_vars:
  all:
    ansible_user: root
    ansible_become: false
    testing: false
    disable_restricted_sysctl: true
