hosts:
  floatapp1:
    ansible_host: 37.218.241.84
    groups: [backend]
    ip: 37.218.241.84
    ip_vpn0: 172.16.1.1
  floatrp1:
    ansible_host: 37.218.241.85
    groups: [frontend]
    ip: 37.218.241.85
    ip_vpn0: 172.16.1.2
  gateway1:
    ansible_host: 37.218.242.191
    groups: [openvpn]
    ip: 37.218.242.216
    ip_vpn0: 172.16.1.3
    egress_ip: 37.218.242.191
    location: Amsterdam
  gateway2:
    ansible_host: 204.13.164.252
    groups: [openvpn]
    ip: 204.13.164.252
    ip6: 2620:13:4000:4000:8080::252
    ip_vpn0: 172.16.1.4
    egress_ip: 204.13.164.252
    gateway_address6: 2620:13:4000:4000:8080::252
    location: Seattle
group_vars:
  all:
    ansible_user: root
    ansible_become: false
    testing: false
    disable_restricted_sysctl: true
