hosts:
  floatapp1:
    ansible_host: 37.218.241.85
    groups: [backend]
    ip: 37.218.241.85
    ip_vpn0: 172.16.1.1
  floatrp1:
    ansible_host: 37.218.242.216
    groups: [frontend]
    ip: 37.218.242.216
    ip_vpn0: 172.16.1.2
  gateway1:
    ansible_host: 37.218.242.217
    groups: [openvpn]
    ip: 37.218.242.217
    ip_vpn0: 172.16.1.3
    gateway_address: 37.218.242.192
    gateway_address6: 2001:db8:123::1
    location: Seattle
group_vars:
  all:
    ansible_user: root
    ansible_become: false
    testing: false
    disable_restricted_sysctl: true
