---
- import_playbook: float/playbooks/all.yml

- hosts: openvpn
  roles:
    - kresd
    - openvpn

- hosts: bridge
  roles:
    - bridge

- hosts: menshen 
  roles:
    - provider
    - leap-prometheus
    - menshen

- hosts: frontend
  roles: [menshen-frontend]
