---
- import_playbook: ../../float/playbooks/all.yml
- import_playbook: config/playbooks/all.yml

- hosts: openvpn
  roles: [openvpn]

- hosts: frontend
  roles: [openvpn-frontend]

- hosts: vpnweb
  roles: [vpnweb]

- hosts: frontend
  roles: [vpnweb-frontend]
