---

# This runs before everything else because it sets facts that are
# consumed by float's "frontend" Ansible role.
- hosts: frontend
  roles: [openvpn-early-setup]

- import_playbook: float/playbooks/all.yml
- import_playbook: config/playbooks/all.yml

- hosts: openvpn
  roles:
    - openvpn
    - kresd
    - geoip

- hosts: frontend
  roles: [openvpn-frontend]

- hosts: vpnweb
  roles:
    - vpnweb
    - leap-prometheus
    - getmyip

- hosts: frontend
  roles: [vpnweb-frontend]
