---
- import_playbook: float/playbooks/all.yml
- import_playbook: config/playbooks/all.yml

- hosts: openvpn
  roles:
    - openvpn
    - kresd

- hosts: vpnweb
  roles:
    - vpnweb
    - leap-prometheus
    - menshen

- hosts: frontend
  roles: [vpnweb-frontend]
