---
- import_playbook: float/playbooks/all.yml
- import_playbook: config/playbooks/all.yml

- hosts: openvpn
  roles:
    - openvpn
    - kresd
    - geoip

- hosts: frontend
  roles: [openvpn-frontend]

- hosts: vpnweb
  roles:
    - vpnweb
    - leap-prometheus
    - getmyip

- hosts: frontend
  roles: [vpnweb-frontend]
