{
 "title": "Authentication",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(service:auth_requests:rate5m, service)"
   }
  ]
 },
 "panels": [
  { "title": "SSO Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SSO grants by service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sso_grants_total[10m])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "SSO logins",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(auth_requests{service='sso',status='ok'}[10m])) by (status,mechanism)",
     "legendFormat": "{{status}} ({{mechanism}})"
    }
   ]
  },
  { "title": "Keystore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Unlocked keys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(keystored_decrypted_keys_total[30m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Key Cache Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "keystored_keys_total", "legendFormat": "{{host}}" }
   ]
  },
  { "title": "Auth Server / $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "service" },
  {
   "title": "Authentication req/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service:auth_requests:rate5m{service=~\"$service\"}",
     "legendFormat": "{{service}}/{{status}}"
    }
   ]
  },
  {
   "title": "Authentication failure pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - service:auth_requests_ok:ratio{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Authentication latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "50pct"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "99pct"
    }
   ]
  },
  { "title": "Auth Server / $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Authentication req/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service:auth_requests:rate5m{service=~\"$service\"}",
     "legendFormat": "{{service}}/{{status}}"
    }
   ]
  },
  {
   "title": "Authentication failure pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - service:auth_requests_ok:ratio{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Authentication latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "50pct"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "99pct"
    }
   ]
  },
  { "title": "Auth Server / $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Authentication req/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service:auth_requests:rate5m{service=~\"$service\"}",
     "legendFormat": "{{service}}/{{status}}"
    }
   ]
  },
  {
   "title": "Authentication failure pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - service:auth_requests_ok:ratio{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Authentication latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "50pct"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "99pct"
    }
   ]
  },
  { "title": "Auth Server / $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Authentication req/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service:auth_requests:rate5m{service=~\"$service\"}",
     "legendFormat": "{{service}}/{{status}}"
    }
   ]
  },
  {
   "title": "Authentication failure pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - service:auth_requests_ok:ratio{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Authentication latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "50pct"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "99pct"
    }
   ]
  },
  { "title": "Auth Server / $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Authentication req/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service:auth_requests:rate5m{service=~\"$service\"}",
     "legendFormat": "{{service}}/{{status}}"
    }
   ]
  },
  {
   "title": "Authentication failure pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - service:auth_requests_ok:ratio{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Authentication latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "50pct"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(auth_latency_bucket{service=~\"$service\"}[10m])) by (service,le))",
     "legendFormat": "99pct"
    }
   ]
  }
 ]
}