{
 "title": "DNS",
 "description": "Bind9 DNS Service Statistics.",
 "tags": [
  "bind",
  "dns",
  "bind-exporter",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "host", "label": "Host:", "query": { "query": "label_values(bind_up, host)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(bind_up, job)" } },
   {
    "name": "view",
    "query": {
     "query": "label_values(bind_resolver_cache_rrsets, view)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(bind_incoming_queries_total{host=~\"$host\"}[$__rate_interval])) by ()",
     "legendFormat": "qps"
    }
   ]
  },
  {
   "title": "Queries (by host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(bind_incoming_queries_total{host=~\"$host\"}[$__rate_interval])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resolver Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(bind_resolver_queries_total{host=~\"$host\",view=~\"$view\"}[$__rate_interval])) by (host, view)",
     "legendFormat": "{{host}}/{{view}}"
    }
   ]
  },
  {
   "title": "Authoritative Queries (by host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(bind_incoming_queries_total{host=~\"$host\"}[$__rate_interval])) by (host) - sum(rate(bind_resolver_queries_total{host=~\"$host\"}[$__rate_interval])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(bind_query_errors_total{host=~\"$host\"}[$__rate_interval])) by (host,error) / ignoring(error) group_left sum(rate(bind_incoming_queries_total{host=~\"$host\"}[$__rate_interval])) by (host)",
     "legendFormat": "{{host}}/{{error}}"
    }
   ]
  }
 ]
}