{
 "title": "Float services",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(svcmap, float_service)"
    }
   },
   {
    "name": "vhosts",
    "query": {
     "query": "label_values(vhostmap{float_service=\"$service\"}, vhost)"
    }
   },
   {
    "name": "unit",
    "label": "Service",
    "query": {
     "query": "label_values(svcmap{float_service=\"$service\"}, service)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(up{service=\"$service\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP qps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, global:nginx_http_requests_total:rate5m{vhost=~\"^.*($vhosts)\"} > 0)",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  { "title": "$unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "unit" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cgroup_cpu_usage{mode=\"user\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/user"
    },
    {
     "expr": "rate(group_cpu_usage{mode=\"system\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/sys"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cgroup_memory_usage{service=\"$unit.service\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cgroup_blkio_bytes{service=\"$unit.service\"}[5m])) by (host,mode)",
     "legendFormat": "{{mode}}/{{host}}"
    }
   ]
  },
  { "title": "$unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cgroup_cpu_usage{mode=\"user\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/user"
    },
    {
     "expr": "rate(group_cpu_usage{mode=\"system\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/sys"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cgroup_memory_usage{service=\"$unit.service\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cgroup_blkio_bytes{service=\"$unit.service\"}[5m])) by (host,mode)",
     "legendFormat": "{{mode}}/{{host}}"
    }
   ]
  },
  { "title": "$unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cgroup_cpu_usage{mode=\"user\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/user"
    },
    {
     "expr": "rate(group_cpu_usage{mode=\"system\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/sys"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cgroup_memory_usage{service=\"$unit.service\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cgroup_blkio_bytes{service=\"$unit.service\"}[5m])) by (host,mode)",
     "legendFormat": "{{mode}}/{{host}}"
    }
   ]
  },
  { "title": "$unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cgroup_cpu_usage{mode=\"user\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/user"
    },
    {
     "expr": "rate(group_cpu_usage{mode=\"system\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/sys"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cgroup_memory_usage{service=\"$unit.service\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cgroup_blkio_bytes{service=\"$unit.service\"}[5m])) by (host,mode)",
     "legendFormat": "{{mode}}/{{host}}"
    }
   ]
  },
  { "title": "$unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cgroup_cpu_usage{mode=\"user\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/user"
    },
    {
     "expr": "rate(group_cpu_usage{mode=\"system\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/sys"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cgroup_memory_usage{service=\"$unit.service\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cgroup_blkio_bytes{service=\"$unit.service\"}[5m])) by (host,mode)",
     "legendFormat": "{{mode}}/{{host}}"
    }
   ]
  },
  { "title": "$unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cgroup_cpu_usage{mode=\"user\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/user"
    },
    {
     "expr": "rate(group_cpu_usage{mode=\"system\",service=\"$unit.service\"}[5m])",
     "legendFormat": "{{host}}/sys"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cgroup_memory_usage{service=\"$unit.service\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cgroup_blkio_bytes{service=\"$unit.service\"}[5m])) by (host,mode)",
     "legendFormat": "{{mode}}/{{host}}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }, "repeat": "job" },
  {
   "title": "Internal HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\",service=\"$service\"}[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}