{
 "title": "Host overview",
 "tags": [
  "prometheus",
  "drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(node_boot_time_seconds, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU: utilization",
   "type": "graph",
   "description": "See $cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{mode!=\"idle\",host=~\"$server\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{mode=\"idle\",host=~\"$server\"}))",
     "legendFormat": "{{mode}} "
    }
   ]
  },
  {
   "title": "CPU: saturation (load avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{host=~\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{host=~\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{host=~\"$server\"}",
     "legendFormat": "load 15m"
    },
    {
     "expr": "sum(count(node_cpu_seconds_total{job=\"node\",mode=\"idle\",host=~\"$server\"}) by (cpu))",
     "legendFormat": "CPUs"
    }
   ]
  },
  {
   "title": "Memory: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$server\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Cached_bytes{host=~\"$server\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$server\"} - node_memory_Writeback_bytes{host=~\"$server\"} - node_memory_Cached_bytes{host=~\"$server\"} - node_memory_Buffers_bytes{host=~\"$server\"} - node_memory_MemFree_bytes{host=~\"$server\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{host=~\"$server\"}[$__rate_interval])",
     "legendFormat": "pages/swpin"
    },
    {
     "expr": "rate(node_vmstat_pswpout{host=~\"$server\"}[$__rate_interval])",
     "legendFormat": "pages/swpout"
    }
   ]
  },
  {
   "title": "Network: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*sum(irate(node_network_receive_bytes_total{host=~\"$server.*\",device=~\"(e.+)[0-9]*\"}[$__rate_interval]) > 0)",
     "legendFormat": "rx/bytes"
    },
    {
     "expr": "8*sum(irate(node_network_transmit_bytes_total{host=~\"$server.*\",device=~\"(e.+)[0-9]*\"}[$__rate_interval]) > 0)",
     "legendFormat": "tx/bytes"
    }
   ]
  },
  {
   "title": "Network: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_drop_total{host=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[$__rate_interval]) + irate(node_network_receive_drop_total{host=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[$__rate_interval])",
     "legendFormat": "drop/{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{host=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[$__rate_interval]) + irate(node_network_receive_errs_total{host=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[$__rate_interval])",
     "legendFormat": "err/{{device}}"
    }
   ]
  },
  {
   "title": "Disk: utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{host=~\"$server\",device=~\"([vs]d[a-z]+|nvme.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "sum(node_md_state{host=~\"$server\",state!=\"active\"}) by (device,state) > 0",
     "legendFormat": "{{device}}: {{state}}"
    }
   ]
  },
  {
   "title": "Disk: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{host=~\"$server.*\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_md_is_active{host=~\"$server\"} < 1",
     "legendFormat": "md_inactive/{{device}}"
    }
   ]
  },
  {
   "title": "Socket: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_tw{host=~\"$server\"}",
     "legendFormat": "tcp/timewait"
    },
    {
     "expr": "node_sockstat_UDP_inuse{host=~\"$server\"}",
     "legendFormat": "udp/inuse"
    },
    {
     "expr": "node_sockstat_TCP_inuse{host=~\"$server\"}",
     "legendFormat": "tcp/inuse"
    }
   ]
  },
  {
   "title": "Socket: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InErrs{host=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "tcp/inerrs"
    },
    {
     "expr": "rate(node_netstat_Tcp_AttemptFails{host=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "tcp/attemptfails"
    },
    {
     "expr": "rate(node_netstat_Udp_RcvbufErrors{host=~\"$server.*\"}[$__rate_interval]) + rate(node_netstat_Udp_SndbufErrors{host=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "udp/buferr"
    },
    {
     "expr": "rate(node_netstat_Udp_InErrors{host=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "udp/inerrs"
    },
    {
     "expr": "rate(node_netstat_Icmp_InErrors{host=~\"$server.*\"}[$__rate_interval]) + rate(node_netstat_Icmp_OutErrors{host=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "icmp/errs"
    }
   ]
  },
  {
   "title": "misc: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{host=~\"$server.*\"} / node_filefd_maximum{host=~\"$server.*\"}",
     "legendFormat": "fd usage %",
     "target": "isNonNull()"
    },
    {
     "expr": "node_procs_running{host=~\"$server.*\"}",
     "legendFormat": "procs running",
     "target": "isNonNull()"
    },
    {
     "expr": "node_nf_conntrack_entries{host=~\"$server.*\"} / node_nf_conntrack_entries_limit{host=~\"$server.*\"}",
     "legendFormat": "conntrack usage %",
     "target": "isNonNull()"
    },
    { "expr": "node_", "legendFormat": "interrupts", "target": "isNonNull()" }
   ]
  },
  {
   "title": "misc: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{host=~\"$server.*\"}",
     "legendFormat": "procs blocked",
     "target": "isNonNull()"
    },
    {
     "expr": "node_entropy_available_bits{host=~\"$server.*\"}",
     "legendFormat": "entropy bytes available",
     "target": "isNonNull()"
    }
   ]
  },
  {
   "title": "misc: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_edac_uncorrectable_errors_total{host=\"$server.*\"}[$__rate_interval])",
     "legendFormat": "edac uncorrectable",
     "target": "isNonNull()"
    },
    {
     "expr": "node_textfile_scrape_error{host=\"$server.*\"}",
     "legendFormat": "textfile scrape error",
     "target": "isNonNull()"
    },
    {
     "expr": "rate(node_edac_correctable_errors_total{host=\"$server.*\"}[$__rate_interval])",
     "legendFormat": "edac correctable",
     "target": "isNonNull()"
    }
   ]
  },
  {
   "title": "filesystem: utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1- (node_filesystem_avail_bytes{host=~\"$server\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_size_bytes{host=~\"$server\"})",
     "legendFormat": "{{mountpoint}} (bytes, {{fstype}})"
    },
    {
     "expr": "1- (node_filesystem_files_free{host=~\"$server\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_files{host=~\"$server\"})",
     "legendFormat": "{{mountpoint}} (inodes, {{fstype}})"
    }
   ]
  }
 ]
}