{
 "title": "Network",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Network traffic by host (IN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "instance:network_receive_bytes_total:rate5m * 8",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Public traffic by host (IN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "instance:public_network_receive_bytes_total:rate5m * 8",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Aggregate traffic (IN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(instance:public_network_receive_bytes_total:rate5m) * 8",
     "legendFormat": "public"
    },
    {
     "expr": "sum(instance:network_receive_bytes_total:rate5m) * 8",
     "legendFormat": "global"
    }
   ]
  },
  {
   "title": "Network traffic by host (OUT)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "instance:network_transmit_bytes_total:rate5m * 8",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Public traffic by host (OUT)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "instance:public_network_transmit_bytes_total:rate5m * 8",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Aggregate traffic (OUT)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(instance:public_network_transmit_bytes_total:rate5m) * 8",
     "legendFormat": "public"
    },
    {
     "expr": "sum(instance:network_transmit_bytes_total:rate5m) * 8",
     "legendFormat": "global"
    }
   ]
  },
  {
   "title": "CPU usage, per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instance_utilization:rate5m", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Public traffic by host (packets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(instance:node_network_packets_total:rate5m{device=~\"en.*\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(instance:node_network_errs_total:rate5m{device=~\"en.*\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}