{
 "title": "Service overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(cgroup_cpu_usage, service)"
    }
   },
   {
    "name": "vhosts",
    "query": {
     "query": "query_result(sum (vhostmap{service=\"$service.service\"}) by (vhost))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cgroup_cpu_usage{mode=\"user\",service=\"$service.service\"}[$__rate_interval])",
     "legendFormat": "{{host}}/user"
    },
    {
     "expr": "rate(group_cpu_usage{mode=\"system\",service=\"$service.service\"}[$__rate_interval])",
     "legendFormat": "{{host}}/sys"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cgroup_memory_usage{service=\"$service.service\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cgroup_blkio_bytes{service=\"$service.service\"}[$__rate_interval])) by (host,mode)",
     "legendFormat": "{{mode}}/{{host}}"
    }
   ]
  },
  {
   "title": "HTTP qps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "repeat": "vhosts",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "global:nginx_http_requests_total:rate5m{vhost=\"$vhosts\"}",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  { "title": "Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "service" },
  {
   "title": "Container Digest",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_digest{service=\"$service\"}) by (digest)",
     "legendFormat": "{{digest}}"
    }
   ]
  }
 ]
}