{
 "title": "Syslog",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=\"rsyslog\"}, host)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(rsyslog_queue_size, job)"
    }
   },
   {
    "name": "queue",
    "query": {
     "query": "label_values(rsyslog_queue_size{job=\"$job\",queue!~\"to_exporter.*\"}, queue)"
    }
   }
  ]
 },
 "panels": [
  { "title": "End-To-End", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "End-to-End latency (across all hosts)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99, log_collection_e2e_duration_seconds)",
     "legendFormat": "99pct"
    },
    {
     "expr": "quantile(0.5, log_collection_e2e_duration_seconds)",
     "legendFormat": "50pct"
    }
   ]
  },
  { "title": "Forwarding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Logs sent (rsyslog omfwd actions/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsyslog_action_processed:rate5m{job=\"rsyslog\",action=\"action-2-builtin:omfwd\",host=~\"^$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsyslog_queue_discarded:rate5m{job=\"$job\",host=~\"$host\"} > 0",
     "legendFormat": "{{host}}/{{queue}}"
    }
   ]
  },
  { "title": "Queue $queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "queue" },
  {
   "title": "Logs/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rsyslog_queue_enqueued{job=\"$job\",queue=\"$queue\",host=~\"$host\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsyslog_queue_size{job=\"$job\",queue=\"$queue\",host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rsyslog_queue_full{job=\"$job\",queue=\"$queue\",host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Trouble", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Suspended Actions",
   "type": "table",
   "description": "Rsyslog is having trouble sending messages to some destinations, check its logs to figure out why.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "sum(rsyslog_action_suspended) without (instance, job, service) > 0"
    }
   ]
  }
 ]
}