{
 "title": "System Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Configuration versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(float_configuration_fingerprint) by (fp)",
     "legendFormat": "{{fp}}"
    }
   ]
  },
  {
   "title": "Unreachable hosts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(target:probe_success:count{probe=\"ping\"}) - count(target:probe_success:sum{probe=\"ping\"})"
    }
   ]
  },
  {
   "title": "Kernel Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(node_uname_info, \"kernel_version\", \"$1\", \"release\", \"(.*)-\\\\w+\")) by (kernel_version)  ",
     "legendFormat": "{{kernel_version}}"
    }
   ]
  },
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Global alerts",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\",scope=\"global\"} > 0"
    }
   ]
  }
 ]
}