---

- name: Install auth-server package
  apt:
    name: auth-server
    state: present

- user:
    name: auth-server
    groups: auth-server-credentials
    append: true

- file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: auth-server
    mode: 0750
  with_items:
    - /etc/auth-server
    - /etc/auth-server/backends.d
    - /etc/auth-server/services.d

- name: Install auth-server configuration
  template:
    src: auth-server.yml.j2
    dest: /etc/auth-server/config.yml
    owner: root
    group: auth-server
    mode: 0640
  notify: restart auth-server

- name: Install auth-server defaults file
  copy:
    src: auth-server.default
    dest: /etc/default/auth-server
  notify: restart auth-server

- name: Enable auth-server systemd unit
  systemd:
    name: auth-server.socket
    enabled: yes
    masked: no
