---

# Set the CN from the loop iterator.
- set_fact:
    cn: "{{ item.name }}.{{ domain_public[0] }}"
  when: "not item.get('domains')"
- set_fact:
    cn: "{{ item.domains[0] }}"
  when: "item.get('domains')"

# Create a self-signed SSL certificate if the ACME-managed one does
# not exist. The 'cn' variable, required by the public-ssl-cert role,
# is defined by the set_fact directive above.
- include_role:
    name: float-util-public-ssl-cert
