groups:
- name: roles/prometheus/files/rules/alerts_disk.conf
  rules:
  - alert: DiskWillFillIn4Hours
    expr: predict_linear(node_filesystem_free_bytes{job="node"}[1h], 4 * 3600) < 0
    for: 5m
    labels:
      severity: page
      scope: host
    annotations:
      summary: 'Disk {{ $labels.mountpoint }} on {{ $labels.instance }} is almost full'
      description: 'Disk {{ $labels.mountpoint }} on {{ $labels.instance }} will be full in less than 4 hours'
      runbook: '[[ alert_playbook_url ]]/DiskWillFillIn4Hours.md'
