# use the sspki plugin to create a cert that is signed by the internal CA to
# authenticate menshen

- include_role:
    name: sspki
  vars:
    sspki:
      name: menshen
      SANs:
        - "menshen.{{ domain_public[0] }}"
      ca: "{{ credentials_dir }}/common/api_ca.crt"
      ca_key: "{{ credentials_dir }}/common/api_ca.key"

- name: Restart nginx because certificate has changed
  systemd:
    name: nginx.service
    state: restarted
  when: sspki_sign.changed

- name: Add the nginx user to the menshen-sspki group
  user:
    name: nginx
    groups: menshen-sspki
    append: yes

- name: Install menshen nginx configuration
  template:
    src: menshen.conf.j2
    dest: /etc/nginx/sites-available/menshen.conf
  notify: reload NGINX

- name: Enable menshen nginx configuration
  file:
    dest: /etc/nginx/sites-enabled/menshen.conf
    src: ../sites-available/menshen.conf
    state: link
  notify: reload NGINX

