- name: Install Grafana piechart plugin
  copy:
    src: "files/grafana/plugins"
    dest: "/var/lib/grafana"
    owner: 'docker-prometheus'
    group: 'docker-prometheus'
  notify: "restart grafana-server"

- name: Install Grafana dashboards
  copy:
    src: "{{ item }}"
    dest: "/etc/grafana/dashboards/"
  with_fileglob: "files/grafana/dashboards/*.json"
  notify: "restart grafana-server"

