---

- name: reload firewall
  systemd:
    name: firewall.service
    state: restarted

- listen: "restart docker-openvpn-openvpn"
  systemd:
    name: "docker-openvpn-openvpn.service"
    state: restarted

- listen: "reload systemd"
  systemd:
    daemon_reload: yes

- listen: add gateway address
  shell: '/usr/local/sbin/add_egress_ip.sh'
