---
provider_config:
  name: "demo provider"
  description: "this is a demo provider"
  domain: 'demo.bitmask.net:8000'
  api_uri: 'api.demo.bitmask.net:8000'
  ca_cert_uri: 'https://api.demo.bitmask.net:8000/ca.crt'
