---

# Set the global apt HTTP proxy to the value of 'apt_proxy'. This
# will cover the default package sources (so we don't have to mangle
# sources.list). For https sources though we're going to have to use
# the awful {% if %} construct inline, to inject the apt_proxy in
# the apt_repository itself. See the docker role for an example.
- name: Install apt proxy
  when: apt_proxy is defined
  template:
    src: 90proxy.j2
    dest: /etc/apt/apt.conf.d/90proxy

- name: Disable apt proxy
  when: apt_proxy is not defined
  file:
    state: absent
    dest: /etc/apt/apt.conf.d/90proxy

- name: Configure apt
  copy:
    src: "apt/{{ item }}"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
  with_items:
    - 02periodic
    - 03no-recommends
    - 50unattended-upgrades

- name: Setup apt trusted keyring
  copy:
    src: "apt/deb_autistici_org.gpg"
    dest: "/usr/share/keyrings/deb.autistici.org.gpg"

- name: Remove legacy apt keyring
  file:
    path: "/etc/apt/trusted.gpg.d/deb_autistici_org.gpg"
    state: absent

- name: Remove legacy repositories
  apt_repository:
    repo: "{{ item }}"
    state: absent
    update_cache: no
  loop:
    - "deb http://deb.autistici.org/urepo ai3/"
    - "deb http://deb.autistici.org/urepo buster-podman/"

- name: Install our standard sources.list
  template:
    src: "sources.list.j2"
    dest: "/etc/apt/sources.list"
  register: sources_list

- name: Install package repositories
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/deb.autistici.org.gpg] http://deb.autistici.org/urepo float/{{ item }}/"
    state: "{{ 'present' if item == float_debian_dist else 'absent' }}"
  loop:
    - stretch
    - buster
    - bullseye

- name: Run apt update
  apt:
    update_cache: yes
    cache_valid_time: '{{ 1800 if ansible_distribution_release == float_debian_dist else 1 }}'
  changed_when: false

# If we're updating the distro, the first round of 'apt upgrade'
# (staggered, to handle normal software upgrades) did not do anything,
# but now we have to run 'apt full-upgrade' because we've just
# switched sources.list, and we're expecting the rest of the playbook
# to execute with the new float_debian_dist.
- name: Run apt full-upgrade
  apt:
    upgrade: "full"
  when: "sources_list.changed"

# When testing, try to make dpkg faster by disabling fsync.
- name: Speed up dpkg
  apt:
    name: dpkg-eatmydata
    state: present
  when: "testing|default(True)"

# Remove legacy stretch/buster mtail package pin.
- name: Cleanup mtail package pin
  file:
    path: "/etc/apt/preferences.d/99float-syslog"
    state: absent

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - unattended-upgrades
      - systemd-coredump
      - rsync
      - git
      - ntp
      - openssl
      - curl
      - lsof
      - cgroups-exporter
      - logcat
      - tabacco
      - restic
      - litestream
      - runcron
      - acpid
      - zstd
      - man-db
      - jq
      - gpg
      - firewall
      - rsyslog
      - rsyslog-relp
      - rsyslog-exporter
      - mtail
      - auditd
      - audisp-json
      - prometheus-node-exporter
      - prometheus-node-exporter-collectors
      - assetmon

- name: Install extra packages
  apt:
    name: "{{ extra_packages }}"
    state: present
  vars:
    extra_packages:
      - net-tools
      - vim
  when: "not testing|default(True)"

- name: Remove blacklisted packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - nfs-common
      - rpcbind
