---

- name: Install fail2ban
  apt:
    name=fail2ban
    state=present

- name: copy configuration file
  template:
    src: jail.local.debian.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: ensure fail2ban runs
  service:
    name=fail2ban
    state=started
    enabled=yes
