---
- name: Install freeipmi packages and dependency
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - freeipmi-tools
      - gawk # node-exporter-freeipmi.awk dependency

- name: Remove ipmitool, not used anymore
  apt:
    name: ipmitool
    state: absent

- name: Disable prometheus node-exporter ipmitool sensor
  systemd:
    name: prometheus-node-exporter-ipmitool-sensor.timer
    state: stopped
    enabled: no

- name: Install freeipmi node-exporter script
  copy:
    src: "node-exporter-freeipmi.awk"
    dest: "/usr/lib/float/node-exporter-freeipmi.awk"
