# Enable serial output for logins and kernel/GRUB (if running GRUB)

- name: Enable getty on serial port
  systemd:
    name: "getty@ttyS{{ serial_port_unit }}"
    enabled: yes
    state: started

- name: Check GRUB availability
  stat:
    path: "/usr/sbin/update-grub"
  register: grub_present

- name: Configure kernel and GRUB to use the serial port
  template:
    src: grub-serial.j2
    dest: /etc/default/grub.d/30-float-serial.cfg
  notify:
    - update-grub
  when: grub_present.stat.exists == true
