---

- name: Install mtail systemd socket unit
  copy:
    src: "mtail.socket"
    dest: "/etc/systemd/system/mtail.socket"
  notify: restart mtail

- name: Install mtail systemd unit
  copy:
    src: "mtail.service"
    dest: "/etc/systemd/system/mtail.service"
  notify: restart mtail

- file:
    path: /etc/mtail
    state: directory

- name: Install mtail programs
  copy:
    src: "{{ item }}"
    dest: /etc/mtail/
  with_fileglob:
    - "files/mtail/*.mtail"
  notify: restart mtail

- name: Cleanup obsolete mtail programs
  file:
    path: "/etc/mtail/counter.mtail"
    state: absent

- file:
    path: /etc/systemd/system/rsyslog.service.d
    state: directory

- name: Configure rsyslog systemd unit to require mtail
  copy:
    src: rsyslog-mtail.conf
    dest: /etc/systemd/system/rsyslog.service.d/mtail.conf
  register: mtail_systemd

- name: Configure rsyslog systemd unit
  copy:
    src: rsyslog-timeout.conf
    dest: /etc/systemd/system/rsyslog.service.d/timeout.conf
  register: rsyslog_systemd

- systemd: daemon_reload=yes
  when: "mtail_systemd is changed or rsyslog_systemd is changed"

- name: Configure rsyslog
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify: restart rsyslog

- name: Configure journald
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
  notify: restart journald
