
stages:
  - docker_build
  - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  BUILD_DIR: build-$CI_JOB_ID

.base_test_template: &base_test
  stage: test
  image: registry.git.autistici.org/ai3/docker/float-runner:bullseye
  before_script:
    - mkdir -p $BUILD_DIR
  script:
    - >
      ./float create-env
      --domain=example.com
      --services=${TEST_DIR}/services.yml
      --passwords=${TEST_DIR}/passwords.yml
      --num-hosts=1
      ${LIBVIRT:+-e libvirt.remote_host=${LIBVIRT#*@} -e libvirt.remote_user=${LIBVIRT%@*}}
      -e ansible_cfg.defaults.strategy=mitogen_linear ${MITOGEN:+-e ansible_cfg.defaults.strategy_plugins=${MITOGEN}/ansible_mitogen/plugins/strategy}
      ${APT_PROXY:+-e config.apt_proxy=${APT_PROXY}}
      $CREATE_ENV_VARS $BUILD_DIR

    - with-ssh-key ./scripts/floatup.py ${LIBVIRT:+--ssh $LIBVIRT} --inventory $BUILD_DIR/hosts.yml --ram 2048 --cpu 2 --image ${VM_IMAGE:-buster} up
    - with-ssh-key ./test-driver init --no-vagrant $BUILD_DIR
    - with-ssh-key ./test-driver run $BUILD_DIR
  after_script:
    - with-ssh-key ./test-driver cleanup --no-vagrant $BUILD_DIR
    - with-ssh-key ./scripts/floatup.py ${LIBVIRT:+--ssh $LIBVIRT} down
  variables:
    CREATE_ENV_VARS: ""
    TEST_DIR: ""
  tags: [ai3]
  artifacts:
    when: on_failure
    expire_in: 1 week
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - "${BUILD_DIR}/ansible.log"
      - "${BUILD_DIR}/logs"

base_test:
  <<: *base_test
  variables:
    TEST_DIR: "test/base.ref"

base_bullseye_test:
  <<: *base_test
  variables:
    VM_IMAGE: "bullseye"
    CREATE_ENV_VARS: "-e config.float_debian_dist=bullseye -e inventory.group_vars.vagrant.ansible_python_interpreter=/usr/bin/python3"
    TEST_DIR: "test/base.ref"

full_test:
  <<: *base_test
  variables:
    TEST_DIR: "test/full.ref"

full_bullseye_test:
  <<: *base_test
  variables:
    VM_IMAGE: "bullseye"
    CREATE_ENV_VARS: "-e config.float_debian_dist=bullseye -e inventory.group_vars.vagrant.ansible_python_interpreter=/usr/bin/python3"
    TEST_DIR: "test/full.ref"

docker_build_and_release_tests:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.git.autistici.org
    - cd test && docker build --build-arg ci_token=$CI_JOB_TOKEN --pull -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:integration-test
    - docker push $CI_REGISTRY_IMAGE:integration-test
  only:
    changes:
      - test/float_integration_test/**
    refs:
      - master

