---

# Disable systemd services that should not be enabled (because the
# associated service was rescheduled elsewhere).
- name: Disable unwanted systemd units
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
    masked: yes
    no_block: yes
  ignore_errors: true
  with_items: "{{ float_disabled_systemd_units }}"

# Also clear failed status if any for disabled units
- name: Reset failed unwanted systemd units
  command: "systemctl reset-failed {{ float_disabled_systemd_units | join(' ') }}"
  ignore_errors: true
