---

- name: Install prometheus config files in /etc/default
  copy:
    src: "node-exporter.default"
    dest: "/etc/default/prometheus-node-exporter"
  notify:
    - reload prometheus-node-exporter

- name: Install prometheus node package
  apt:
    name: prometheus-node-exporter
    state: present

- name: Add static metrics
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/prometheus/node-exporter/{{ item }}"
  with_items:
    - roles.prom
    - vhostmap.prom

# Treat ansible.prom specially: since it contains a timestamp of
# the push, it changes every time, and we don't want to report
# it when running with --check.
- name: Add push metrics
  template:
    src: ansible.prom.j2
    dest: "/var/lib/prometheus/node-exporter/ansible.prom"
  changed_when: false

# System scripts (e.g. runcron) can drop metric files as any user
- name: Setup node-exporter world-writable textfile directory
  file:
    path: "/var/lib/prometheus/node-exporter"
    state: directory
    mode: 01777

- name: Enable prometheus node systemd unit
  systemd:
    name: "prometheus-node-exporter.service"
    enabled: yes
    state: started

- name: Mask node-exporter smartmon.sh, replaced by smartmon.py
  systemd:
    name: "prometheus-node-exporter-smartmon.service"
    enabled: no
    masked: yes

# Script and cron job to periodically run shell scripts that generate
# Prometheus metrics for the local node (collected via the node exporter).
- name: Install node-exporter-cron script
  copy:
    src: node-exporter-cron.sh
    dest: "/usr/local/bin/node-exporter-cron"
    mode: 0755

- name: Install node-exporter-cron cron job
  copy:
    dest: "/etc/cron.d/node-exporter-scripts"
    content: "2-59/5 * * * * root /usr/local/bin/node-exporter-cron\n"

- name: Create node-exporter scripts directory
  file:
    path: "/etc/prometheus/node-exporter-scripts"
    state: directory

- name: Install node-exporter-scripts
  copy:
    dest: "/etc/prometheus/node-exporter-scripts/{{ item.path }}"
    src: "{{ item.src }}"
    mode: 0755
  with_filetree: files/node-exporter-scripts/
  when: item.state == 'file'

- name: Remove obsolete apt.sh
  file:
    path: "/etc/prometheus/node-exporter-scripts/apt.sh"
    state: absent
