---

stunnel_global_key:
  stunnel_setuid: "setuid"
  stunnel_setgid: "setgid"
  stunnel_pid: "pid"
  stunnel_foreground: "foreground"
  stunnel_debug: "debug"
  stunnel_log: "log"
  stunnel_output: "output"
  stunnel_syslog: "syslog"
  stunnel_fips: "fips"
  stunnel_chroot: "chroot"
  stunnel_compression: "compression"
  stunnel_egd: "EGD"
  stunnel_engine: "engine"
  stunnel_engine_ctrl: "engineCtrl"
  stunnel_engine_default: "engineDefault"
  stunnel_rnd_bytes: "RNDbytes"
  stunnel_rnd_overwrite: "RNDoverwrite"
  stunnel_service: "service"
  stunnel_socket: "socket"
  stunnel_options: "options"
  stunnel_cert: "cert"
  stunnel_key: "key"
  stunnel_ca_file: "CAfile"
  stunnel_ssl_version: "sslVersion"
  stunnel_verify: "verify"

stunnel_services_key:
  accept: "accept"
  ca_path: "CApath"
  ca_file: "CAfile"
  cert: "cert"
  check_email: "checkEmail"
  check_host: "checkHost"
  check_ip: "checkIP"
  ciphers: "ciphers"
  client: "client"
  config: "config"
  connect: "connect"
  crl_path: "CRLpath"
  crl_file: "CRLfile"
  curve: "curve"
  log_id: "logId"
  debug: "debug"
  delay: "delay"
  engine_id: "engineId"
  engine_num: "engineNum"
  exec: "exec"
  exec_args: "execArgs"
  failover: "failover"
  ident: "ident"
  include: "include"
  key: "key"
  libwrap: "libwrap"
  local: "local"
  sni: "sni"
  ocsp: "OCSP"
  ocspaia: "OCSPaia"
  ocspflag: "OCSPflag"
  options: "options"
  protocol: "protocol"
  protocol_authentication: "protocolAuthentication"
  protocol_domain: "protocolDomain"
  protocol_host: "protocolHost"
  protocol_password: "protocolPassword"
  protocol_username: "protocolUsername"
  psk_identity: "PSKidentity"
  psk_secrets: "PSKsecrets"
  pty: "pty"
  redirect: "redirect"
  renegotiation: "renegotiation"
  reset: "reset"
  retry:  "retry"
  setgid: "setgid"
  setuid: "setuid"
  session_cache_size: "sessionCacheSize"
  session_cache_timeout: "sessionCacheTimeout"
  sessond: "sessiond"
  ssl_version: "sslVersion"
  stack: "stack"
  timeout_busy: "TIMEOUTbusy"
  timeout_close: "TIMEOUTclose"
  timeout_connect: "TIMEOUTconnect"
  timeout_idle: "TIMEOUTidle"
  transparent: "transparent"
  verify: "verify"

