---

- name: stunnel | stunnel.conf
  template:
    src: "stunnel.conf.j2"
    dest: "{{ stunnel_conf }}"
    owner: root
    group: root
    mode: 0644
  notify: restart stunnel

- name: stunnel | enable service
  lineinfile:
    dest: /etc/default/stunnel4
    state: present
    regexp: ^ENABLED=
    line: ENABLED=1
  notify: restart stunnel
