# For openvpn service, we want little of what float offers: we do not want a
# reverse proxy or haproxy setup, we do not want ACME certificates. Because
# reverse proxies are connection based, so if we want to support UDP, we cannot
# treat these how float typically treats services.
#
# We do want DNS, but it is 'special', in float, because we don't want to point
# it at the reverse proxy hosts, but rather at the public IPs (or gateway ips)
# of the hosts in the 'openvpn' group.
#
# So we to treat openvpn as a user-facing service, and just rely on DNS that we
# manage, outside of float, for request routing and balancing.

- name: Install Openvpn DNS records
  template:
    src: 'openvpn_dns.j2'
    dest: '/etc/dns/manual/openvpn.yml'
  notify: reload openvpn DNS config

