{
 "title": "Host overview",
 "tags": [
  "prometheus",
  "drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU: utilization",
   "type": "graph",
   "description": "See $cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$server\"}[5m])) / scalar(count(node_cpu_seconds_total{mode=\"idle\",instance=~\"$server\"}))",
     "legendFormat": "{{mode}} "
    }
   ]
  },
  {
   "title": "CPU: saturation (load avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "load 15m"
    },
    {
     "expr": "sum(count(node_cpu_seconds_total{job=\"node\",mode=\"idle\",instance=~\"$server\"}) by (cpu))",
     "legendFormat": "CPUs"
    }
   ]
  },
  {
   "title": "Memory: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_Writeback_bytes{instance=~\"$server\"} - node_memory_Cached_bytes{instance=~\"$server\"} - node_memory_Buffers_bytes{instance=~\"$server\"} - node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=~\"$server\"}[5m])",
     "legendFormat": "pages/swpin"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=~\"$server\"}[5m])",
     "legendFormat": "pages/swpout"
    }
   ]
  },
  {
   "title": "Network: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*sum(irate(node_network_receive_bytes_total{instance=~\"$server.*\",device=~\"(e.+)[0-9]*\"}[5m]) > 0)",
     "legendFormat": "rx/bytes"
    },
    {
     "expr": "8*sum(irate(node_network_transmit_bytes_total{instance=~\"$server.*\",device=~\"(e.+)[0-9]*\"}[5m]) > 0)",
     "legendFormat": "tx/bytes"
    }
   ]
  },
  {
   "title": "Network: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) + irate(node_network_receive_drop_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m])",
     "legendFormat": "drop/{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) + irate(node_network_receive_errs_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m])",
     "legendFormat": "err/{{device}}"
    }
   ]
  },
  {
   "title": "Disk: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$server\",device=~\"([vs]d[a-z]+|nvme.+)\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{instance=~\"$server.*\",device=~\"([vs]d[a-z]+|nvme.+)\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_md_is_active{instance=~\"$server\"} < 1",
     "legendFormat": "md_inactive/{{device}}"
    }
   ]
  },
  {
   "title": "Socket: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$server\"}",
     "legendFormat": "tcp/timewait"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$server\"}",
     "legendFormat": "udp/inuse"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$server\"}",
     "legendFormat": "tcp/inuse"
    }
   ]
  },
  {
   "title": "Socket: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=~\"$server.*\"}[5m])",
     "legendFormat": "tcp/inerrs"
    },
    {
     "expr": "rate(node_netstat_Tcp_AttemptFails{instance=~\"$server.*\"}[5m])",
     "legendFormat": "tcp/attemptfails"
    },
    {
     "expr": "rate(node_netstat_Udp_RcvbufErrors{instance=~\"$server.*\"}[5m]) + rate(node_netstat_Udp_SndbufErrors{instance=~\"$server.*\"}[5m])",
     "legendFormat": "udp/buferr"
    },
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=~\"$server.*\"}[5m])",
     "legendFormat": "udp/inerrs"
    },
    {
     "expr": "rate(node_netstat_Icmp_InErrors{instance=~\"$server.*\"}[5m]) + rate(node_netstat_Icmp_OutErrors{instance=~\"$server.*\"}[5m])",
     "legendFormat": "icmp/errs"
    }
   ]
  },
  {
   "title": "misc: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$server.*\"} / node_filefd_maximum{instance=~\"$server.*\"}",
     "legendFormat": "fd usage %",
     "target": "isNonNull()"
    },
    {
     "expr": "node_procs_running{instance=~\"$server.*\"}",
     "legendFormat": "procs running",
     "target": "isNonNull()"
    },
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$server.*\"} / node_nf_conntrack_entries_limit{instance=~\"$server.*\"}",
     "legendFormat": "conntrack usage %",
     "target": "isNonNull()"
    },
    { "expr": "node_", "legendFormat": "interrupts", "target": "isNonNull()" }
   ]
  },
  {
   "title": "misc: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=~\"$server.*\"}",
     "legendFormat": "procs blocked",
     "target": "isNonNull()"
    },
    {
     "expr": "node_entropy_available_bits{instance=~\"$server.*\"}",
     "legendFormat": "entropy bytes available",
     "target": "isNonNull()"
    }
   ]
  },
  {
   "title": "misc: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_edac_uncorrectable_errors_total{instance=\"$server.*\"}[5m])",
     "legendFormat": "edac uncorrectable",
     "target": "isNonNull()"
    },
    {
     "expr": "node_textfile_scrape_error{instance=\"$server.*\"}",
     "legendFormat": "textfile scrape error",
     "target": "isNonNull()"
    },
    {
     "expr": "rate(node_edac_correctable_errors_total{instance=\"$server.*\"}[5m])",
     "legendFormat": "edac correctable",
     "target": "isNonNull()"
    }
   ]
  },
  {
   "title": "filesystem: utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1- (node_filesystem_avail_bytes{instance=~\"$server\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_size_bytes{instance=~\"$server\"})",
     "legendFormat": "{{mountpoint}} (bytes, {{fstype}})"
    },
    {
     "expr": "1- (node_filesystem_files_free{instance=~\"$server\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_files{instance=~\"$server\"})",
     "legendFormat": "{{mountpoint}} (inodes, {{fstype}})"
    }
   ]
  }
 ]
}