{
 "title": "HTTP",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "vhost",
    "label": "Host",
    "query": "label_values(global:nginx_http_requests_total:rate5m, vhost)"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS by vhost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(global:nginx_http_requests_total:rate5m{vhost=~\"^$vhost$\"}) by (vhost))",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  {
   "title": "Errors by code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(nginx_http_requests{vhost=~\"^$vhost\",code=~\"[45].*\"}[5m])) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "QPS by backend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(nginx_http_requests{vhost=~\"^$vhost$\"}[5m])) by (backend))",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Error percentage (5XX)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, global:nginx_http_requests_errs:rate5m{vhost=~\"^$vhost$\"} / global:nginx_http_requests_total:rate5m{vhost=~\"^$vhost$\"})",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_http_requests_ms{vhost=~\"^$vhost$\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/50pct"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(nginx_http_requests_ms{vhost=~\"^$vhost$\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/90pct"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_requests_ms{vhost=~\"^$vhost$\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/99pct"
    }
   ]
  },
  {
   "title": "Cache Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "global:nginx_http_cached_requests:ratio{vhost=~\"^$vhost\"}",
     "legendFormat": "{{cache_status}}"
    }
   ]
  }
 ]
}