{
 "title": "All services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "label_values(up, host)" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, service:cpu_usage:rate1m{host=~\"^$host$\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(cgroup_memory_usage{host=~\"^$host$\"}) by (service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU (sum)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(service:cpu_usage:rate1m{host=~\"^$host$\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory (sum)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(cgroup_memory_usage{host=~\"^$host$\"})",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}