# this is a recursive copy
- name: Install obfs4 state
  copy:
    src: "{{ credentials_dir }}/obfs4/"
    dest: "/opt/obfsvpn/data"
    owner: docker-obfsvpn
    group: docker-obfsvpn
    mode: 0640

- name: Install firewall config for obfsvpn
  copy:
    src: "50obfsvpn.firewall"
    dest: "/etc/firewall/filter.d/50obfsvpn"
  notify: "reload firewall"

- name: Make sure obfs4 state file ownership is correct
  file:
    path: "/opt/obfsvpn/data/obfs4_state.json"
    owner: docker-obfsvpn
    group: docker-obfsvpn
    mode: 0640

- name: Make sure obfs4 obfs4_bridgeline.txt file ownership is correct
  file:
    path: "/opt/obfsvpn/data/obfs4_cert.txt"
    owner: docker-obfsvpn
    group: docker-obfsvpn
    mode: 0640

- name: Create data dir for kcp and other obfs modes
  file:
    path: "/opt/obfsvpn/data/{{ item }}"
    state: directory
    owner: "docker-obfsvpn-{{ item }}"
    group: "docker-obfsvpn"
  with_items:
    - "kcp"

- name: adding existing user docker-obfsvpn-kcp to group docker-obfsvpn
  user:
    name: docker-obfsvpn-kcp
    groups: docker-obfsvpn
    append: yes
