#!/bin/sh
#
# Get the ansible-vault password from a GPG-encrypted file in the
# repository pointed at by the FLOAT_VAULT_PASSWORD_FILE environment variable.
#

if [ -z "${FLOAT_VAULT_PASSWORD_FILE}" ]; then
    echo "Error: FLOAT_VAULT_PASSWORD_FILE is not defined, don't know where to find the trust root repository" >&2
    exit 2
fi

if [ ! -e "${FLOAT_VAULT_PASSWORD_FILE}" ]; then
    echo "Error: could not find ansible-vault GPG-encrypted password file in ${FLOAT_VAULT_PASSWORD_FILE}" >&2
    exit 1
fi

# Find a gpg executable.
if [ -z "${GPG}" ]; then
    GPG=$(which gpg2)
    if [ -z "${GPG}" ]; then
        GPG=$(which gpg)
        if [ -z "${GPG}" ]; then
            echo "Could not find a gnupg executable!" >&2
            exit 1
        fi
    fi
fi

exec 2>/dev/null
exec ${GPG} -d "${FLOAT_VAULT_PASSWORD_FILE}"
