---

- user:
    name: "log-collector"
    system: yes
    home: "/var/log/remote"
    groups: ["log-collector-credentials"]
  
# Setup Elasticsearch, if enabled.
- include_tasks: elasticsearch.yml
  when: enable_elasticsearch

# Setup the rsyslog-collector instance. Needs packages from
# stretch-backports, to support modern versions of Elasticsearch.
- name: Install rsyslog-elasticsearch package from backports
  apt:
    name: rsyslog-elasticsearch
    default_release: "{{ 'stretch-backports' if ansible_distribution_release == 'stretch' else '' }}"
    state: present
- name: Create the rsyslog-collector logs dir
  file:
    path: "/var/log/remote"
    state: directory
    owner: "log-collector"
    mode: 0700
- name: Install logrotate script for local files
  template:
    src: "log-collector.logrotate.j2"
    dest: "/etc/logrotate.d/log-collector"
- name: Install rsyslog-collector.conf
  template:
    src: "rsyslog-collector.conf.j2"
    dest: "/etc/rsyslog-collector.conf"
  notify: "restart rsyslog-collector"
- name: Install rsyslog-collector systemd unit
  template:
    src: "rsyslog-collector.service.j2"
    dest: "/etc/systemd/system/rsyslog-collector.service"
  notify: "restart rsyslog-collector"
- name: Create the rsyslog-collector normalization rules dir
  file:
    path: /etc/rsyslog-collector-lognorm
    state: directory
- name: Install rsyslog-collector normalization rules
  copy:
    src: "{{ item }}"
    dest: "/etc/rsyslog-collector-lognorm/{{ item | regex_replace('^.*/', '') }}"
  with_fileglob:
    - files/lognorm/*
  notify: "restart rsyslog-collector"
