---

# Setup Elasticsearch, if enabled.
- include_tasks: elasticsearch.yml
  when: enable_elasticsearch

- name: Create the rsyslog-collector logs dir
  file:
    path: "/var/log/remote"
    state: directory
    owner: "docker-log-collector"
    mode: 0700
- name: Create the rsyslog-collector spool dir
  file:
    path: "/var/spool/rsyslog-collector"
    state: directory
    owner: docker-log-collector
    mode: 0700
- name: Install logrotate script for local files
  template:
    src: "log-collector.logrotate.j2"
    dest: "/etc/logrotate.d/log-collector"
- name: Install rsyslog-collector.conf
  template:
    src: "rsyslog-collector.conf.j2"
    dest: "/etc/rsyslog-collector.conf"
  notify: "restart rsyslog-collector"
- name: Create the rsyslog-collector normalization rules dir
  file:
    path: /etc/rsyslog-collector-lognorm
    state: directory
- name: Install rsyslog-collector normalization rules
  copy:
    src: "{{ item }}"
    dest: "/etc/rsyslog-collector-lognorm/{{ item | regex_replace('^.*/', '') }}"
  with_fileglob:
    - files/lognorm/*
  notify: "restart rsyslog-collector"

# TODO: remove when no longer necessary.
- name: Remove legacy rsyslog-collector service
  systemd:
    name: rsyslog-collector.service
    state: stopped
    enabled: no
    masked: yes
  ignore_errors: true

- name: Remove old rsyslog-collector systemd unit
  file:
    path: "/etc/systemd/system/rsyslog-collector.service"
    state: absent

