---

- name: restart tabacco-metadb
  systemd:
    name: tabacco-metadb.service
    state: restarted
  # Allow failure when testing backups, the unit can't start until later.
  ignore_errors: "{{ testing | default(True) }}"

