groups:
  - name: roles/float-infra-prometheus/templates/rules/alerts_syslog.conf
    rules:
      - alert: SyslogDroppingLogs
        expr: rsyslog_queue_discarded:rate5m{job="rsyslog-collector"} > 0.04
        for: 15m
        labels:
          scope: global
          severity: page
        annotations:
          description: 'Syslog collector is dropping logs on {{ $labels.host }}'
          summary: 'Syslog collector is dropping logs'
          runbook: '[[ alert_runbook_fmt | format("SyslogDroppingLogs") ]]'

      - alert: MtailNotProcessingLogs
        expr: rate(mtail_lines_total[10m]) == 0
        for: 1h
        labels:
          scope: host
          severity: page
        annotations:
          summary: 'Mtail is stuck'
          description: 'Mtail is not processing logs on {{ $labels.host }}, try restarting mtail.socket.'
          runbook: '[[ alert_runbook_fmt | format("MtailNotProcessingLogs") ]]'

