groups:
- name: roles/float-infra-prometheus/templates/rules/alerts_cpu.conf
  rules:
  - alert: CPUUsageHigh
    expr: instance_utilization:rate5m > 0.96
    for: 10m
    labels:
      scope: host
      severity: warn
    annotations:
      summary: 'CPU utilization is high on {{ $labels.host }}'
      description: 'CPU utilization is high on {{ $labels.host }}'

  # The following alert is used as a signal to inhibit most alerts when
  # a host is obviously thrashing.
  - alert: HostThrashing
    expr: node_load5 > 100
    for: 5m
    labels:
      scope: host
      severity: page
    annotations:
      summary: 'Host {{$labels.host}} is thrashing'
      description: 'Load average on host {{$labels.host}} is very high ({{$value}}), the host is likely unresponsive.'
      runbook: '[[ alert_runbook_fmt | format("HostThrashing") ]]'

  # The threshold here is set to 1 instead of 0 on purpose, to allow
  # low frequency throttling events, which shouldn't be problematic.
  - alert: ThermalEnvelopeThrottling
    expr: (host:node_cpu_core_throttles_total:rate5m > 1) or (host:node_cpu_package_throttles_total:rate5m > 1)
    for: 2h
    labels:
      scope: host
      severity: warn
    annotations:
      summary: 'Host {{$labels.host}} is running too hot'
      description: |
        The CPU on {{$labels.host}} is being throttled because it is running too hot.

  # PSI alerts - in testing mode for now.
  - alert: HostMemoryPressureHigh
    expr: rate(node_pressure_memory_waiting_seconds_total[10m]) > 0.2
    for: 10m
    labels:
      scope: host
      severity: warn
    annotations:
      summary: "High memory pressure on host {{$labels.host}}"
      description: |
        PSI metrics report high memory pressure on host {{$labels.host}}:
          {{$value}} > 0.2.
        Processes might be at risk of eventually OOMing.

  # PSI alerts - in testing mode for now.
  - alert: HostCPUPressureHigh
    expr: rate(node_pressure_cpu_waiting_seconds_total[10m]) > 0.2
    for: 10m
    labels:
      scope: host
      severity: warn
    annotations:
      summary: "High CPU pressure on host {{$labels.host}}"
      description: |
        PSI metrics report high CPU pressure on host {{$labels.host}}:
          {{$value}} > 0.2.
        The host might become unresponsive due to contention on CPU time.
