groups:
- name: roles/float-infra-prometheus/template/rules/alerts_disk.conf
  rules:
  - alert: DiskWillFillIn4Hours
    expr: (predict_linear(node_filesystem_free_bytes[1h], 4 * 3600) < 0) and (node_filesystem_free_bytes / node_filesystem_size_bytes < 0.6)
    for: 30m
    labels:
      severity: page
      scope: host
    annotations:
      summary: 'Disk {{ $labels.mountpoint }} on {{ $labels.host }} is almost full'
      description: 'Disk {{ $labels.mountpoint }} on {{ $labels.host }} will be full in less than 4 hours'
      runbook: '[[ alert_runbook_fmt | format("DiskWillFillIn") ]]4Hours'
