# note this is currently riseup-specific, see
# https://0xacab.org/leap/container-platform/lilypad/-/issues/44
# before enabling
include:
  - ../float/services.yml.default
  - "services.bitmask.yml"

prometheus-pushgateway:
  scheduling_group: backend
  num_instances: 1
  monitoring_endpoints:
    - job_name: prometheus-pushgateway
      port: 9091
      scheme: http
  containers:
    - name: prometheus-pushgateway
      image: registry.0xacab.org/leap/container-platform/prometheus-pushgateway:1-0
      port: 9091

ooni-exporter:
  scheduling_group: backend
  num_instances: 1
  containers:
    - name: ooni-exporter
      image: registry.0xacab.org/leap/ooni-exporter:1.0
      env:
        OONI_PUSH_PORT: 9091
        OONI_PUSH_HOST: "prometheus-pushgateway"
