---

- name: Install haproxy
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - haproxy
      - hatop

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Install firewall config
  template:
    src: firewall/20haproxy.j2
    dest: /etc/firewall/filter.d/20haproxy
  notify: "reload firewall"

