---
- name: Create cert and CA directories
  file:
    path: /etc/leap/ca
    state: directory
    group: docker-menshen
    mode: 0750

- name: Create key directory
  file:
    path: /etc/leap/keys
    state: directory
    group: docker-menshen
    owner: docker-menshen
    mode: 0750

- name: Install menshen client_ca key
  copy:
    src: "{{ credentials_dir }}/common/client_ca.key"
    dest: "/etc/leap/keys"
    owner: docker-menshen
    mode: 0640
  notify:
    - "restart docker-menshen-menshen"
- name: Install menshen client_ca cert
  copy:
    src: "{{ credentials_dir }}/common/client_ca.crt"
    dest: "/etc/leap/ca"
    owner: docker-menshen
    mode: 0444
  notify:
    - "restart docker-menshen-menshen"

# Needed for bonafide operation
- name: Install provider key used for API endpoint
  copy:
    src: "{{ credentials_dir }}/common/api_ca.key"
    dest: "/etc/leap/keys"
    owner: docker-menshen
    mode: 0640
  notify:
    - "restart docker-menshen-menshen"

- name: Install provider CA cert for API endpoint
  copy:
    src: "{{ credentials_dir }}/common/api_ca.crt"
    dest: "/etc/leap/ca"
    owner: docker-menshen
    mode: 0444
  notify:
    - "restart docker-menshen-menshen"

- name: Create menshen mount point for storing persistent files
  file:
    path: /opt/menshen/
    state: directory
    group: docker-menshen
    mode: 0750
