#!/bin/bash
# Detect if a different image has been pulled

set -u

image=${1:-}

if [ -z "$image" ]; then
  echo "usage: <image url>"
  exit 1
fi

pre_version=$(podman inspect --type image  --format "{{.Id}}" $image)

podman pull $image

if [ $? -gt 0 ]; then
  exit 1
fi

post_version=$(podman inspect --type image  --format "{{.Id}}" $image)

if [ "$pre_version" == "$post_version" ]; then
  exit 42
fi
