# install the provider.json
- name: "Create directory for provider.json to live"
  file:
    path: "/etc/leap/config"
    state: directory

- name: "Render the provider.json template"
  template:
    src: 'provider-config.json.j2'
    dest: '/etc/leap/config/provider.json'

# Make sure the endpoint CA is available at {{ provider_domain }}/ca.crt
# eg. https://black.riseup.net/ca.crt
- name: "Install LEAP Endpoint CA (ca.crt)"
  copy:
    src: "{{ credentials_dir }}/common/api_ca.crt"
    dest: "/etc/leap/config/ca.crt"

