# Use the sspki role to create the credentials: the openvpn server certificate
# for the gateway, signed by the LEAP API endpoint+gateway CA.

- include_role:
    name: sspki
  vars:
    sspki:
      name: openvpn
      ca: "{{ credentials_dir }}/common/api_ca.crt"
      ca_key: "{{ credentials_dir }}/common/api_ca.key"

- name: Create cert and CA directories
  file:
    path: /etc/leap/ca
    state: directory
    group: docker-openvpn
    mode: 0755

- name: Create credentials key directory
  file:
    path: /etc/leap/keys
    state: directory
    group: docker-openvpn
    mode: 0750

- name: Install DH parameters
  copy:
    src: "{{ credentials_dir }}/x509/dhparam"
    dest: /etc/leap/keys/dh.pem
    mode: 0640

- name: Install client certificate generating and API endpoint CA bundle
  copy:
    src: "{{ credentials_dir }}/common/leap_ca_bundle.crt"
    dest: /etc/leap/ca/leap_ca_bundle.crt
    mode: 0444
