- name: Check the OpenVPN gateway certificate
    x509_csr:
      credentials_name: openvpn
      domain: "{{ domain_public[0] }}"
      mode: server
      params:  { names: [ 'openvpn' ] }
      private_key_path: "{{ credentials_dir}}/openvpn/{{ domain_public[0] }}_private.key"
      cert_path: "{{ credentials_dir}}/openvpn/{{ domain_public[0] }}_cert.crt"
      ca_cert_path: "{{ credentials_dir }}/common/ca.crt"
      check: true
    check_mode: no
    register: openvpn_x509_should_update

- name: Create the OpenVPN gateway CSR
  x509_csr:
    credentials_name: openvpn
    domain: "{{ domain_public[0] }}"
    mode: server
    params: { names: [ 'openvpn' ] }
    private_key_path: "{{ credentials_dir }}/openvpn/{{ domain_public[0] }}_private.key"
    check: false
  when: "openvpn_x509_should_update.changed"
  register: openvpn_x509_csr

  - name: Create the OpenVPN gateway certificate
    x509_sign:
      csr: "{{ openvpn_x509_csr.csr }}"
      mode: server
      ca_cert_path: "{{ credentials_dir }}/common/ca.crt"
      ca_key_path: "{{ credentials_dir }}/common/ca_private.key"
    when: "openvpn_x509_should_update.changed"
    register: openvpn_x509_sign

- name: Install the signed certificate for OpenVPN
  copy:
    dest: "{{ credentials_dir}}/openvpn/{{ domain_public[0] }}_leap.crt"
    content: "{{ openvpn_x509_sign.cert }}"
    mode: 0644
  when: "openvpn_x509_sign.changed"

- name: Create credentials directories
  file:
    path: "{{ item }}"
    state: directory
    group: docker-openvpn
    mode: 0755
  with_items:
    - /etc/leap/certs
    - /etc/leap/ca

- name: Create credentials key directory
  file:
    path: /etc/leap/keys
    state: directory
    group: docker-openvpn
    mode: 0750

- name: Install DH parameters
  copy:
    src: "{{ credentials_dir }}/x509/dhparam"
    dest: /etc/leap/keys/dh.pem
    mode: 0640

- name: Install client certificate generating and API endpoint CA bundle
  copy:
    src: "{{ credentials_dir }}/common/leap_ca_bundle.crt"
    dest: /etc/leap/ca/leap_ca_bundle.crt
    mode: 0444
