- name: Create openvpn directory
  file:
    path: /etc/openvpn
    state: directory
    group: docker-openvpn
    mode: 0750

- name: Install firewall filter config for openvpn
  template:
    src: "50openvpn.firewall.j2"
    dest: "/etc/firewall/filter.d/50openvpn"
  notify: "reload firewall"

- name: Install firewall nat config for vpnweb
  template:
    src: "50openvpn_nat.firewall.j2"
    dest: "/etc/firewall/nat.d/50openvpn"
  notify: "reload firewall"

- name: Install openvpn configs
  template:
    src: "{{ item }}"
    dest: "/etc/openvpn"
    mode: 0644
  with_items:
    - udp.conf.j2
    - tcp.conf.j2
  notify:
    - "restart docker-openvpn-openvpn"
