---
- name: Setup secondary egress address
  template:
    src: 'add_egress_ip.j2'
    dest: '/usr/local/sbin/add_egress_ip.sh'
    mode: '0744'
  notify: add gateway address
  when: egress_ip is defined

- name: Ensure egress address is added on reboot
  cron:
    name: "add gateway address"
    special_time: reboot
    job: '/usr/local/sbin/add_egress_ip.sh'
  when: egress_ip is defined
