{
 "title": "OpenVPN Stats",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [ "openvpn" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": { "query": "label_values(openvpn_up, host)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 19, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_up{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total Gateway Network",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "instance:network_receive_bytes_total:rate5m{host=~\"$host\"}",
     "legendFormat": "{{host}} Rx"
    },
    {
     "expr": "instance:network_transmit_bytes_total:rate5m{host=~\"$host\"}",
     "legendFormat": "{{host}} Tx"
    },
    {
     "expr": "sum(irate(instance_network_receive_bytes{host=~\"$host\"}[5m]))",
     "legendFormat": "Receive 2"
    },
    {
     "expr": "sum(irate(instance_network_transmit_bytes{host=~\"$host\"}[5m]))",
     "legendFormat": "Transmit 2"
    }
   ]
  },
  {
   "title": "Clients connected (all endpoints)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openvpn_server_connected_clients{status_path=\"/tmp/openvpn-status-tcp\"})",
     "legendFormat": "tcp"
    },
    {
     "expr": "sum(openvpn_server_connected_clients{status_path=\"/tmp/openvpn-status-udp\"})",
     "legendFormat": "udp"
    }
   ]
  },
  {
   "title": "Clients connected (tcp)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openvpn_server_connected_clients{status_path=\"/tmp/openvpn-status-tcp\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Clients connected (udp)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "openvpn_server_connected_clients{status_path=\"/tmp/openvpn-status-udp\",host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU: utilization",
   "type": "graph",
   "description": "non-idle CPU usage",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((avg by (host) (rate(node_cpu_seconds_total{host=~\"$host\",mode=\"idle\"}[5m]))) * 100)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Gateway Connection Tracking",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{host=~\"$host\"}",
     "legendFormat": "{{host}} entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{host=~\"$host\"}",
     "legendFormat": "{{host}} limit"
    }
   ]
  }
 ]
}