---

- name: Install Grafana config (dirs)
  file:
    path: "/etc/grafana/{{ item.path }}"
    state: directory
    owner: root
    group: docker-prometheus
    mode: 0750
  with_filetree: templates/grafana/
  when: item.state == 'directory'

- name: Install Grafana config (files)
  template:
    src: "{{ item.src }}"
    dest: "/etc/grafana/{{ item.path }}"
    owner: root
    group: docker-prometheus
    mode: 0640
    variable_start_string: "[["
    variable_end_string: "]]"
  with_filetree: templates/grafana/
  when: item.state == 'file'
  notify: restart grafana

- name: Create Grafana database directory
  file:
    path: "/var/lib/grafana"
    state: directory
    owner: docker-prometheus
    mode: 0700
