groups:
- name: roles/prometheus/files/rules/alerts_system_health.conf
  rules:
    - alert: DiskUnhealthy
      expr: smartmon_device_smart_healthy < 1
      for: 2h
      labels:
        severity: warn
      annotations:
        summary: "Disk {{ $labels.disk }} on {{ $labels.host }} is unhealthy"
        description: "Disk {{ $labels.disk }} on {{ $labels.host }} is reporting unhealthy SMART status and might need to be replaced."

    - alert: RAIDDeviceUnhealthy
      expr: node_md_degraded > 0
      for: 15m
      labels:
        severity: warn
      annotations:
        summary: "RAID device {{ $labels.md_device }} on {{ $labels.host }} is unhealthy"
        description: "The RAID device {{ $labels.md_device }} on {{ $labels.host }} is reporting a degraded state, which means that probably one or more of the disks in the array have failed."

    - alert: HostPhysicalComponentTooHot
      expr: node_hwmon_temp_celsius / node_hwmon_temp_crit_celsius > 0.95
      for: 2h
      labels:
        severity: page
      annotations:
        summary: "A physical component is running too hot on {{ $labels.host }}"
        description: "A sensor is reporting that a physical component ({{ $labels.sensor }}/{{ $labels.chip }}) on {{ $labels.host }} has been running very close to the critical level ({{ $value }}) for the last 2 hours."

