# use the sspki role to create the credentials directory:
# the sspki role should create the api endpont cert, and the full chain bundle
# (containing the API endpoint CA and the generated cert) and install them

- include_role:
    name: sspki
  vars:
    sspki:
      name: api
      params:
        names: "{{ api_uri }}"
      ca: "{{ credentials_dir }}/common/api_ca.crt"
      ca_key: "{{ credentials_dir }}/common/api_ca.key"

- name: Create cert and CA directories
  file:
    path: /etc/leap/ca
    state: directory
    group: docker-vpnweb
    mode: 0750

- name: Create key directory
  file:
    path: /etc/leap/keys
    state: directory
    group: docker-vpnweb
    mode: 0750

# Needed for vpnweb to issue client certificates
- name: Install vpnweb client_ca key
  copy:
    src: "{{ credentials_dir }}/common/client_ca.key"
    dest: "/etc/leap/keys"
    owner: docker-vpnweb
    mode: 0640
  notify:
    - "restart docker-vpnweb-vpnweb"


- name: Install vpnweb client_ca cert
  copy:
    src: "{{ credentials_dir }}/common/client_ca.crt"
    dest: "/etc/leap/ca"
    owner: docker-vpnweb
    mode: 0444
  notify:
    - "restart docker-vpnweb-vpnweb"

# Needed for bonafide operation
- name: Install provider key used for API endpoint
  copy:
    src: "{{ credentials_dir }}/common/api_ca.key"
    dest: "/etc/leap/keys"
    owner: docker-vpnweb
    mode: 0640
  notify:
    - "restart docker-vpnweb-vpnweb"

- name: Install provider CA cert for API endpoint
  copy:
    src: "{{ credentials_dir }}/common/api_ca.crt"
    dest: "/etc/leap/ca"
    owner: docker-vpnweb
    mode: 0444
  notify:
    - "restart docker-vpnweb-vpnweb"

