
- name: Create cert and CA directories
  file:
    path: /etc/leap/ca
    state: directory
    group: docker-vpnweb
    mode: 0750

- name: Create key directory
  file:
    path: /etc/leap/keys
    state: directory
    group: docker-vpnweb
    mode: 0750

# Needed for vpnweb to issue client certificates
- name: Install vpnweb client_ca key
  copy:
    src: "{{ credentials_dir }}/common/client_ca.key"
    dest: "/etc/leap/keys"
    owner: docker-vpnweb
    mode: 0640
  notify:
    - "restart docker-vpnweb-vpnweb"


- name: Install vpnweb client_ca cert
  copy:
    src: "{{ credentials_dir }}/common/client_ca.crt"
    dest: "/etc/leap/ca"
    owner: docker-vpnweb
    mode: 0444
  notify:
    - "restart docker-vpnweb-vpnweb"

# Needed for bonafide operation
- name: Install provider key used for API endpoint
  copy:
    src: "{{ credentials_dir }}/common/api_ca.key"
    dest: "/etc/leap/keys"
    owner: docker-vpnweb
    mode: 0640
  notify:
    - "restart docker-vpnweb-vpnweb"

- name: Install provider CA cert for API endpoint
  copy:
    src: "{{ credentials_dir }}/common/api_ca.crt"
    dest: "/etc/leap/ca"
    owner: docker-vpnweb
    mode: 0444
  notify:
    - "restart docker-vpnweb-vpnweb"

