# use the sspki role to create the credentials directory:
# the sspki role should create the api endpont cert, and the full chain bundle
# (containing the API endpoint CA and the generated cert) and install them

- include_role:
    name: sspki
  vars:
    sspki:
      name: vpnweb
      ca: "{{ credentials_dir }}/common/api_ca.crt"
      ca_key: "{{ credentials_dir }}/common/api_ca.key"

- name: Create cert and CA directories
  file:
    path: /etc/leap/ca
    state: directory
    group: docker-vpnweb
    mode: 0750

- name: Create key directory
  file:
    path: /etc/leap/keys
    state: directory
    group: docker-vpnweb
    mode: 0750

# The following two items are needed for vpnweb to issue client certificates
- name: Install vpnweb client_ca key
  copy:
    src: "{{ credentials_dir }}/common/client_ca.key"
    dest: "/etc/leap/keys"
    owner: docker-vpnweb
    mode: 0640

- name: Install vpnweb client_ca cert
  copy:
    src: "{{ credentials_dir }}/common/client_ca.crt"
    dest: "/etc/leap/ca"
    owner: docker-vpnweb
    mode: 0444

# Create a fullchain cert bundle containing the API endpoint CA and certificate
- name: Create fullchain cert bundle of CA and generated certificate
  shell: /usr/bin/cat "{{ credentials_dir }}/common/{{ item.sspki.name }}_ca.crt /etc/credentials/public/{{ item.service.name }}/{{ item.sspki.name }}/cert.pem > /etc/credentials/public/{{ item.service.name }}/{{ item.sspki.name }}/fullchain.crt"
  when: sspki_install
  notify: reload NGINX
