- import_tasks: "credentials.yml"

- name: "Generate eip-service.json and provider.json"
  local_action:
    module: simplevpn
    obfs4_state_dir: "{{ credentials_dir }}/shapeshifter"
    locations: "{{ locations }}"
    domain: "{{ domain_public[0] }}"
    provider_description: "{{ provider_config.description }}"
    gateways: "{{ groups['openvpn'] | map('extract', hostvars) | list }}"
    openvpn: "{{ openvpn_config }}"
    provider_api_uri: "https://{{ api_uri }}:4430"
    ca_cert_uri: "https://{{ ca_cert_uri }}"
    ca_public_crt: "{{ credentials_dir }}/common/api_ca.crt"
  run_once: true
  register: simplevpn_result
  notify:
    - "restart docker-vpnweb-vpnweb"


# need to install the api dirs
- name: "Create API versioned directories"
  file:
    path: "/etc/leap/config/vpnweb/{{ item }}"
    state: directory
  with_items:
    - 3

- name: "Render the eip-service.json template"
  template:
    src: 'eip-config.json.j2'
    dest: '/etc/leap/config/vpnweb/3/eip-service.json'
  notify:
    - "restart docker-vpnweb-vpnweb"

- name: "Render the provider.json template"
  template:
    src: 'provider-config.json.j2'
    dest: '/etc/leap/config/vpnweb/provider.json'
  notify:
    - "restart docker-vpnweb-vpnweb"

- import_tasks: "sip.yml"
  when: vpnweb_auth | default('anon') == "sip2"
