- import_tasks: "credentials.yml"

- name: "Create configuration directory for API json files"
  local_action:
    module: file
    path: "{{ playbook_dir }}/config"
    state: directory

- name: "Generate eip-service.json and provider.json"
  local_action:
    module: simplevpn
    obfs4_state_dir: "{{ credentials_dir }}/shapeshifter"
    locations: "{{ locations }}"
    domain: "{{ domain_public[0] }}"
    gateways: "{{ groups['openvpn'] | map('extract', hostvars) | list }}"
    openvpn: "{{ openvpn_config }}"
    provider_api_uri: "{{ api_uri }}"
    ca_cert_uri: "{{ ca_cert_uri }}"
    ca_private_key: "{{ credentials_dir }}/common/client_ca.key"
  run_once: true
  register: simplevpn_result

# need to install the api dirs
- name: "Create API versioned directories"
  file:
    path: "/etc/leap/config/vpnweb/{{ item }}"
    state: directory
  with_items:
    - 1
    - 3

- name: "Render the eip-service.json template"
  template:
    src: 'eip-config.json.j2'
    dest: '/etc/leap/config/vpnweb/3/eip-service.json'

- name: "Render the provider.json template"
  template:
    src: 'provider-config.json.j2'
    dest: '/etc/leap/config/vpnweb/provider.json'

