---

# TODO: switch to keyserver once the apt_key --no-tty bug in Ansible is fixed.
- name: Install podman repository key
  apt_key:
    id: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
    url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4D64390375060AA4'
    state: present

- name: Install podman repository
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /"
    state: present

- name: Install podman packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - podman

- name: Symlink podman to docker
  file:
    src: /usr/bin/podman
    dest: /usr/bin/docker
    state: link
    force: true

- name: Install podman-pull-image script
  copy:
    src: podman-pull-image
    dest: /usr/sbin/podman-pull-image
    mode: 0755
