---

docker_registry_url: ""
docker_registry_username: ""
docker_registry_password: ""

# The following options are not used on >= Buster
docker_daemon_config:
  log-driver: "local"
  log-opts:
    max-size: "10m"
    max-file: "2"
  metrics-addr: "0.0.0.0:9323"
  experimental: true
docker_daemon_config_testing:
  insecure-registries: ["192.168.10.1:5000"]
