# TODO(godog) setup ai-metrics-exporter scraping

- name: Install exporter and deps
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - prometheus-mysqld-exporter
      - python-mysqldb

- include_tasks: user.yml
  vars:
    user: prometheus
    mariadb_max_user_connections: 3

- name: Grant privileges to monitoring user
  mysql_user:
    name: 'prometheus'
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    append_privs: yes
    state: present
    config_file: "{{ mariadb_config }}"

- name: Exporter config directory
  file:
    dest: "{{ mariadb_metrics_config | dirname }}"
    state: directory

- name: Mask default instance
  systemd:
    name: prometheus-mysqld-exporter
    masked: yes
    enabled: no
  notify: "systemctl reset-failed"

- name: Install exporter for {{ mariadb_instance }}
  template:
    src: templates/exporter.service.j2
    dest: /etc/systemd/system/{{ mariadb_metrics_service }}
  register: mariadb_metrics_systemd_unit

- name: Install exporter config for {{ mariadb_instance }}
  template:
    src: templates/exporter.cnf.j2
    dest: "{{ mariadb_metrics_config }}"
  register: mariadb_metrics_systemd_unit

# Explicitly start the service after bootstrapping data directory
- name: Start {{ mariadb_metrics_service }}
  systemd:
    name: "{{ mariadb_metrics_service }}"
    daemon_reload: "{{ mariadb_metrics_systemd_unit is changed }}"
    enabled: yes
    state: "{{ 'restarted' if mariadb_metrics_systemd_unit.changed else 'started' }}"

