---

- file:
    path: "/etc/systemd/system/{{ systemd_unit }}.d"
    state: directory

- name: "Install systemd snippet for {{ systemd_unit }}"
  template:
    src: conf.j2
    dest: "/etc/systemd/system/{{ systemd_unit }}.d/{{ tag }}.conf"
