- hosts: localhost
  gather_facts: no
  become: no
  tasks:
    # Create the openvpn path below credentials_dir that we're going to use.
    - name: "Create paths below {{ credentials_dir }}/openvpn"
      file:
        path: "{{ credentials_dir }}/openvpn"
        state: directory

    - name: Generate the X509 CA certificate
      local_action: x509_ca ca_subject="{{ x509_ca_subject | default('CN=LEAP OpenVPN CA') }}" ca_cert_path="{{ credentials_dir }}/openvpn/ca.pem" ca_key_path="{{ credentials_dir }}/openvpn/ca_private_key.pem"

    - name: Check the certificate for OpenVPN
      x509_csr:
        credentials_name: openvpn
        domain: "{{ domain_public[0] }}"
        mode: server
        params:  { names: [ 'openvpn' ] }
        private_key_path: "{{ credentials_dir}}/openvpn/private_key.pem"
        cert_path: "{{ credentials_dir}}/openvpn/cert.pem"
        ca_cert_path: "{{ credentials_dir }}/openvpn/ca.pem"
        check: true
      check_mode: no
      register: x509_should_update

    - name: Create the CSR for OpenVPN cert
      x509_csr:
        credentials_name: openvpn
        domain: "{{ domain_public[0] }}"
        mode: server
        params: { names: [ 'openvpn' ] }
        private_key_path: "{{ credentials_dir }}/openvpn/private_key.pem"
        check: false
      when: "x509_should_update.changed"
      register: x509_csr

    - name: Create the certificate for OpenVPN
      x509_sign:
        csr: "{{ x509_csr.csr }}"
        mode: server
        ca_cert_path: "{{ credentials_dir }}/openvpn/ca.pem"
        ca_key_path: "{{ credentials_dir }}/openvpn/ca_private_key.pem"
      when: "x509_should_update.changed"
      register: x509_sign

    - name: Install the signed certificate for OpenVPN
      copy:
        dest: "{{ credentials_dir}}/openvpn/cert.pem"
        content: "{{ x509_sign.cert }}"
        mode: 0644
      when: "x509_sign.changed"

- name: Include float init-credentials
  import_playbook: ../float/playbooks/init-credentials.yml
