---

galaxy_info:
  author: Jose Coelho
  description: configure stunnel
  license: MIT
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - system
dependencies: []
