# this is a recursive copy
- name: Install shapeshifter state
  copy:
    src: "{{ credentials_dir }}/shapeshifter/"
    dest: "/srv/leap/shapeshifter-state"
    owner: docker-openvpn
    mode: 0600

- name: Install firewall config for shapeshifter
  copy:
    src: "50shapeshifter.firewall"
    dest: "/etc/firewall/filter.d/50shapeshifter"
  notify: "reload firewall"

- name: Make sure shapeshifter state file ownership is correct
  file:
    path: "/srv/leap/shapeshifter-state/obfs4_state.json"
    owner: docker-openvpn
    mode: 0600

- name: Make sure shapeshifter obfs4_bridgeline.txt file ownership is correct
  file:
    path: "/srv/leap/shapeshifter-state/obfs4_cert.txt"
    owner: docker-openvpn
    mode: 0600

- name: Create openvpn directory
  file:
    path: /etc/openvpn
    state: directory
    group: docker-openvpn
    mode: 0750

- name: Install DH parameters
  copy:
    src: "{{ credentials_dir }}/x509/dhparam"
    dest: /etc/openvpn/dh.pem

- name: Install OpenVPN CA
  copy:
    src: "{{ credentials_dir }}/openvpn/ca.pem"
    dest: /etc/openvpn/ca.pem

- name: Install OpenVPN key
  copy:
    src: "{{ credentials_dir }}/openvpn/private_key.pem"
    dest: /etc/openvpn/private_key.pem

- name: Install OpenVPN cert
  copy:
    src: "{{ credentials_dir }}/openvpn/cert.pem"
    dest: /etc/openvpn/cert.pem

- name: Install firewall config for openvpn
  copy:
    src: "50openvpn.firewall"
    dest: "/etc/firewall/filter.d/50openvpn"
  notify: "reload firewall"

- name: Install openvpn configs
  template:
    src: "{{ item }}"
    dest: "/etc/openvpn"
    mode: 0644
  with_items:
    - udp.conf
    - tcp.conf
    - shapeshifter.conf
  notify:
    - "restart docker-openvpn-openvpn"
