- name: Install shapeshifter state
  copy:
    src: "{{ credentials_dir }}/shapeshifter/"
    dest: "/srv/leap/shapeshifter-state"

- name: Install firewall config for shapeshifter
  copy:
    src: "50shapeshifter.firewall"
    dest: "/etc/firewall/filter.d/50shapeshifter"
  notify: "reload firewall"

